import type { Locale } from "@/lib/i18n";

export const blogSlugs = [
  "small-business-website-cost-montreal",
  "montreal-restaurant-website-checklist",
  "local-seo-checklist-montreal-small-business",
] as const;

export type BlogSlug = (typeof blogSlugs)[number];

export type BlogSection = {
  heading: string;
  paragraphs: string[];
  checklist?: string[];
};

export type BlogArticle = {
  slug: BlogSlug;
  locale: Locale;
  title: string;
  description: string;
  excerpt: string;
  publishedAt: string;
  updatedAt: string;
  author: string;
  intro: string[];
  sections: BlogSection[];
  relatedServiceSlug: string;
};

export type BlogLabels = {
  eyebrow: string;
  indexTitle: string;
  indexDescription: string;
  readArticle: string;
  published: string;
  updated: string;
  by: string;
  checklist: string;
  backToBlog: string;
  relatedTitle: string;
  relatedDescription: string;
  relatedCta: string;
};

export const blogLabels: Record<Locale, BlogLabels> = {
  en: { eyebrow: "Practical guides", indexTitle: "Web design and local growth insights", indexDescription: "Clear, practical guidance for Montreal businesses planning a website, improving a customer journey or strengthening local visibility.", readArticle: "Read article", published: "Published", updated: "Updated", by: "By", checklist: "Checklist", backToBlog: "Back to the blog", relatedTitle: "Need help putting this into practice?", relatedDescription: "Explore the related service and discuss a website shaped around your business.", relatedCta: "View related service" },
  fr: { eyebrow: "Guides pratiques", indexTitle: "Conseils en conception Web et croissance locale", indexDescription: "Des conseils clairs et pratiques pour les entreprises montréalaises qui préparent un site, améliorent le parcours client ou leur visibilité locale.", readArticle: "Lire l’article", published: "Publié le", updated: "Mis à jour le", by: "Par", checklist: "Liste de vérification", backToBlog: "Retour au blogue", relatedTitle: "Besoin d’aide pour passer à l’action?", relatedDescription: "Découvrez le service associé et discutons d’un site adapté à votre entreprise.", relatedCta: "Voir le service associé" },
  es: { eyebrow: "Guías prácticas", indexTitle: "Diseño web y crecimiento local", indexDescription: "Consejos claros y prácticos para negocios de Montreal que planean un sitio web, mejoran la experiencia del cliente o su visibilidad local.", readArticle: "Leer artículo", published: "Publicado", updated: "Actualizado", by: "Por", checklist: "Lista de control", backToBlog: "Volver al blog", relatedTitle: "¿Necesitas ayuda para aplicarlo?", relatedDescription: "Conoce el servicio relacionado y hablemos de un sitio adaptado a tu negocio.", relatedCta: "Ver servicio relacionado" },
  de: { eyebrow: "Praxisleitfäden", indexTitle: "Webdesign und lokales Wachstum", indexDescription: "Klare, praktische Hinweise für Unternehmen in Montreal, die eine Website planen, ihre Customer Journey oder lokale Sichtbarkeit verbessern.", readArticle: "Artikel lesen", published: "Veröffentlicht", updated: "Aktualisiert", by: "Von", checklist: "Checkliste", backToBlog: "Zurück zum Blog", relatedTitle: "Unterstützung bei der Umsetzung?", relatedDescription: "Entdecken Sie die passende Leistung und besprechen Sie eine Website für Ihr Unternehmen.", relatedCta: "Passende Leistung ansehen" },
  it: { eyebrow: "Guide pratiche", indexTitle: "Web design e crescita locale", indexDescription: "Indicazioni chiare e concrete per le attività di Montréal che progettano un sito, migliorano il percorso cliente o la visibilità locale.", readArticle: "Leggi l’articolo", published: "Pubblicato", updated: "Aggiornato", by: "Di", checklist: "Lista di controllo", backToBlog: "Torna al blog", relatedTitle: "Serve aiuto per metterlo in pratica?", relatedDescription: "Scopri il servizio collegato e parliamo di un sito adatto alla tua attività.", relatedCta: "Vedi il servizio collegato" },
  pt: { eyebrow: "Guias práticos", indexTitle: "Web design e crescimento local", indexDescription: "Orientações claras e práticas para empresas de Montreal que planeiam um site, melhoram a jornada do cliente ou a visibilidade local.", readArticle: "Ler artigo", published: "Publicado", updated: "Atualizado", by: "Por", checklist: "Lista de verificação", backToBlog: "Voltar ao blogue", relatedTitle: "Precisa de ajuda para aplicar?", relatedDescription: "Conheça o serviço relacionado e converse sobre um site pensado para a sua empresa.", relatedCta: "Ver serviço relacionado" },
  zh: { eyebrow: "实用指南", indexTitle: "网站设计与本地业务增长", indexDescription: "为蒙特利尔企业提供清晰、可执行的建议，帮助规划网站、改善客户体验并提升本地曝光度。", readArticle: "阅读文章", published: "发布于", updated: "更新于", by: "作者", checklist: "检查清单", backToBlog: "返回博客", relatedTitle: "需要协助落实这些建议？", relatedDescription: "查看相关服务，并讨论如何打造符合您业务需求的网站。", relatedCta: "查看相关服务" },
};

const dates = {
  publishedAt: "2026-07-13",
  updatedAt: "2026-07-13",
  author: "Arash Ammarlooi",
};

const articles: Record<BlogSlug, Record<Locale, BlogArticle>> = {
  "small-business-website-cost-montreal": {
    en: {
      slug: "small-business-website-cost-montreal", locale: "en", ...dates,
      title: "What affects the cost of a small-business website in Montreal?",
      description: "A practical breakdown of the decisions that shape small-business website costs in Montreal, without misleading one-size-fits-all price claims.",
      excerpt: "Understand how scope, content, design, integrations and long-term ownership affect a Montreal website budget.",
      intro: [
        "A useful website estimate starts with scope, not a generic price range. Two businesses may both ask for a five-page site while needing very different research, content, booking tools, languages and approval processes.",
        "The goal is to compare proposals on the same basis: what work is included, what you must supply, what happens after launch and which assumptions could change the estimate.",
      ],
      sections: [
        { heading: "Scope and complexity drive the work", paragraphs: ["A focused brochure site is different from a site with online payments, appointment scheduling, member accounts or a searchable catalogue. Each feature adds interface states, testing, accessibility work and ongoing maintenance. Multilingual publishing also requires a plan for translation, language switching and localized metadata—not simply duplicated pages."], checklist: ["List the pages and the single most important action on each.", "Separate launch essentials from features that can follow later.", "Document integrations, languages and who approves the work."] },
        { heading: "Content and design change the estimate", paragraphs: ["A custom visual system, original photography and professionally written copy take more time than adapting approved brand assets and final text. Content delays can also create repeated layout changes. Ask whether strategy, copy editing, image sourcing, responsive design and revision rounds are included."], checklist: ["Inventory existing text, photos, logo files and brand guidelines.", "Identify who writes, translates and approves each page.", "Request a clear number of concepts and revision rounds."] },
        { heading: "Quality and ownership matter after launch", paragraphs: ["Performance, accessibility, analytics, privacy-aware forms, redirects and technical SEO are part of a dependable launch. Hosting, domain renewal, software updates and support are recurring responsibilities. A lower initial quote can cost more if these items are excluded or the site is difficult to update."], checklist: ["Confirm ownership of the domain, accounts, design and source files.", "Ask what testing, training, backups and post-launch support include.", "Compare proposals by deliverables and exclusions, not the total alone."] },
        { heading: "Prepare a brief before requesting proposals", paragraphs: ["State your audience, business goal, required pages, examples you like, available content, deadline and realistic budget constraints. A good provider should explain trade-offs and suggest phases where appropriate. Treat any estimate given without discovery as preliminary rather than a guaranteed final cost."] },
      ],
      relatedServiceSlug: "small-business-web-design",
    },
    fr: {
      slug: "small-business-website-cost-montreal", locale: "fr", ...dates,
      title: "Qu’est-ce qui influence le coût d’un site Web pour PME à Montréal?",
      description: "Les décisions qui influencent le coût d’un site Web pour PME à Montréal, sans fourchettes universelles trompeuses.",
      excerpt: "Voyez comment la portée, le contenu, le design, les intégrations et la gestion future influencent le budget.",
      intro: ["Une estimation utile commence par la portée du projet, et non par un prix générique. Deux entreprises qui demandent un site de cinq pages peuvent avoir des besoins très différents en stratégie, contenu, réservation, langues et approbations.", "Pour comparer des propositions équitablement, il faut savoir ce qui est inclus, ce que vous devez fournir, les responsabilités après le lancement et les hypothèses qui pourraient modifier le coût."],
      sections: [
        { heading: "La portée et la complexité déterminent l’effort", paragraphs: ["Un site vitrine ciblé n’exige pas le même travail qu’un site avec paiement, prise de rendez-vous, comptes clients ou catalogue filtrable. Chaque fonction ajoute des états d’interface, des essais, de l’accessibilité et de l’entretien. Un site multilingue demande aussi une vraie stratégie de traduction et de référencement."], checklist: ["Dressez la liste des pages et de l’action principale de chacune.", "Séparez les éléments essentiels au lancement des ajouts futurs.", "Précisez les intégrations, les langues et les responsables des approbations."] },
        { heading: "Le contenu et le design modifient l’estimation", paragraphs: ["Une identité visuelle sur mesure, des photos originales et une rédaction professionnelle prennent plus de temps que l’utilisation de contenus déjà approuvés. Demandez si la stratégie, la révision des textes, la recherche d’images, l’adaptation mobile et les cycles de corrections sont compris."], checklist: ["Inventoriez textes, photos, logos et normes graphiques disponibles.", "Attribuez la rédaction, la traduction et l’approbation de chaque page.", "Faites préciser le nombre de concepts et de cycles de révision."] },
        { heading: "La qualité et la propriété comptent à long terme", paragraphs: ["Performance, accessibilité, analytique, formulaires respectueux de la vie privée, redirections et SEO technique font partie d’un lancement solide. Hébergement, domaine, mises à jour et soutien restent des responsabilités récurrentes."], checklist: ["Confirmez qui possède le domaine, les comptes et les fichiers sources.", "Vérifiez les essais, la formation, les sauvegardes et le soutien inclus.", "Comparez les livrables et exclusions, pas seulement le total."] },
        { heading: "Préparez un bon dossier de départ", paragraphs: ["Présentez votre clientèle, l’objectif d’affaires, les pages requises, les références appréciées, le contenu disponible, l’échéancier et vos contraintes budgétaires. Une estimation donnée sans découverte devrait toujours être considérée comme préliminaire."] },
      ], relatedServiceSlug: "small-business-web-design",
    },
    es: {
      slug: "small-business-website-cost-montreal", locale: "es", ...dates,
      title: "¿Qué influye en el coste de una web para pequeñas empresas en Montreal?",
      description: "Los factores que determinan el coste de una web para pequeñas empresas en Montreal, sin promesas ni precios universales.",
      excerpt: "Alcance, contenido, diseño, integraciones y mantenimiento explicados para preparar un presupuesto realista.",
      intro: ["Una estimación útil empieza por el alcance, no por una cifra genérica. Dos negocios pueden pedir cinco páginas y necesitar niveles muy distintos de estrategia, textos, reservas, idiomas y revisiones.", "Compara propuestas sobre la misma base: qué incluye cada una, qué debes aportar, qué ocurrirá después del lanzamiento y qué supuestos pueden cambiar el presupuesto."],
      sections: [
        { heading: "El alcance y la complejidad definen el trabajo", paragraphs: ["Una web informativa no equivale a un sitio con pagos, citas, cuentas de usuario o catálogo filtrable. Cada función requiere estados de interfaz, pruebas, accesibilidad y mantenimiento. Publicar en varios idiomas también exige traducción, navegación y metadatos localizados."], checklist: ["Enumera páginas y la acción principal de cada una.", "Separa lo imprescindible para lanzar de una segunda fase.", "Documenta integraciones, idiomas y responsables de aprobación."] },
        { heading: "El contenido y el diseño afectan la estimación", paragraphs: ["Un sistema visual a medida, fotografía original y redacción profesional requieren más tiempo que usar materiales finales. Pregunta si se incluyen estrategia, edición, imágenes, diseño adaptable y rondas de cambios."], checklist: ["Reúne textos, fotos, logotipos y normas de marca.", "Asigna quién escribe, traduce y aprueba cada página.", "Aclara cuántas propuestas y revisiones incluye el trabajo."] },
        { heading: "Calidad y propiedad después del lanzamiento", paragraphs: ["Rendimiento, accesibilidad, analítica, formularios respetuosos con la privacidad, redirecciones y SEO técnico forman parte de un lanzamiento fiable. Hosting, dominio, actualizaciones y soporte continúan después."], checklist: ["Confirma la propiedad del dominio, cuentas y archivos fuente.", "Pregunta por pruebas, formación, copias y soporte.", "Compara entregables y exclusiones, no solo el total."] },
        { heading: "Prepara un informe claro", paragraphs: ["Explica público, objetivo, páginas, referencias, contenido disponible, plazo y límites presupuestarios. Un proveedor responsable explicará alternativas y fases; cualquier cifra sin descubrimiento previo debe considerarse provisional."] },
      ], relatedServiceSlug: "small-business-web-design",
    },
    de: {
      slug: "small-business-website-cost-montreal", locale: "de", ...dates,
      title: "Was beeinflusst die Kosten einer Website für Kleinunternehmen in Montreal?",
      description: "Ein sachlicher Überblick über die Faktoren einer Website-Kalkulation in Montreal – ohne pauschale Preisversprechen.",
      excerpt: "So beeinflussen Umfang, Inhalte, Design, Integrationen und laufender Betrieb das Budget.",
      intro: ["Eine belastbare Schätzung beginnt beim Leistungsumfang, nicht bei einem pauschalen Preis. Zwei Unternehmen können jeweils fünf Seiten wünschen und dennoch ganz unterschiedlichen Aufwand für Strategie, Inhalte, Buchungen, Sprachen und Freigaben verursachen.", "Vergleichen Sie Angebote auf derselben Grundlage: enthaltene Leistungen, eigene Beiträge, Zuständigkeiten nach dem Start und Annahmen, die den Aufwand verändern können."],
      sections: [
        { heading: "Umfang und Komplexität bestimmen den Aufwand", paragraphs: ["Eine kompakte Informationsseite unterscheidet sich von einer Website mit Zahlungen, Terminbuchung, Kundenkonten oder filterbarem Katalog. Jede Funktion bringt Zustände, Tests, Barrierefreiheit und Wartung mit sich. Mehrsprachigkeit benötigt außerdem Übersetzung, Sprachführung und lokale Metadaten."], checklist: ["Seiten und wichtigste Aktion je Seite auflisten.", "Pflichtumfang zum Start von späteren Ausbaustufen trennen.", "Integrationen, Sprachen und Freigabeverantwortliche dokumentieren."] },
        { heading: "Inhalte und Design verändern die Kalkulation", paragraphs: ["Individuelles Erscheinungsbild, eigene Fotos und professionelle Texte benötigen mehr Zeit als freigegebene Vorlagen. Klären Sie, ob Strategie, Textbearbeitung, Bildsuche, responsive Gestaltung und Korrekturschleifen enthalten sind."], checklist: ["Vorhandene Texte, Bilder, Logos und Markenrichtlinien erfassen.", "Verantwortung für Schreiben, Übersetzen und Freigeben festlegen.", "Anzahl der Entwürfe und Korrekturrunden bestätigen."] },
        { heading: "Qualität und Eigentum nach dem Start", paragraphs: ["Performance, Barrierefreiheit, Analytics, datenschutzbewusste Formulare, Weiterleitungen und technische SEO gehören zu einem soliden Launch. Hosting, Domain, Updates und Support bleiben laufende Aufgaben."], checklist: ["Eigentum an Domain, Konten und Quelldateien klären.", "Tests, Schulung, Backups und Support prüfen.", "Angebote nach Leistungen und Ausschlüssen vergleichen."] },
        { heading: "Ein klares Briefing vorbereiten", paragraphs: ["Beschreiben Sie Zielgruppe, Geschäftsziel, Seiten, Vorbilder, vorhandene Inhalte, Termin und Budgetrahmen. Ein seriöser Anbieter erklärt Kompromisse und mögliche Phasen. Schätzungen ohne vorherige Analyse bleiben vorläufig."] },
      ], relatedServiceSlug: "small-business-web-design",
    },
    it: {
      slug: "small-business-website-cost-montreal", locale: "it", ...dates,
      title: "Cosa determina il costo di un sito per piccole imprese a Montréal?",
      description: "I fattori che incidono sul costo di un sito aziendale a Montréal, senza fasce di prezzo generiche o promesse fuorvianti.",
      excerpt: "Ambito, contenuti, design, integrazioni e gestione futura spiegati in modo pratico.",
      intro: ["Una stima utile parte dall’ambito, non da un prezzo standard. Due imprese possono chiedere cinque pagine ma richiedere quantità molto diverse di strategia, testi, prenotazioni, lingue e revisioni.", "Confronta le proposte sulla stessa base: attività incluse, materiali da fornire, responsabilità dopo il lancio e ipotesi che possono modificare la stima."],
      sections: [
        { heading: "Ambito e complessità definiscono il lavoro", paragraphs: ["Un sito informativo è diverso da uno con pagamenti, appuntamenti, account o catalogo filtrabile. Ogni funzione aggiunge stati dell’interfaccia, test, accessibilità e manutenzione. Il multilingua richiede inoltre traduzioni, navigazione e metadati localizzati."], checklist: ["Elenca pagine e azione principale di ciascuna.", "Separa gli elementi essenziali dalle fasi successive.", "Indica integrazioni, lingue e responsabili delle approvazioni."] },
        { heading: "Contenuti e design cambiano la stima", paragraphs: ["Un’identità su misura, fotografie originali e testi professionali richiedono più tempo rispetto a materiali definitivi già disponibili. Verifica strategia, revisione, immagini, design responsive e cicli di modifiche inclusi."], checklist: ["Raccogli testi, foto, logo e linee guida esistenti.", "Assegna scrittura, traduzione e approvazione.", "Chiarisci numero di proposte e revisioni."] },
        { heading: "Qualità e proprietà nel tempo", paragraphs: ["Prestazioni, accessibilità, analytics, moduli attenti alla privacy, reindirizzamenti e SEO tecnico fanno parte di un lancio affidabile. Hosting, dominio, aggiornamenti e assistenza continuano nel tempo."], checklist: ["Conferma proprietà di dominio, account e file sorgente.", "Chiedi quali test, formazione, backup e supporto sono inclusi.", "Confronta consegne ed esclusioni, non solo il totale."] },
        { heading: "Prepara un brief chiaro", paragraphs: ["Descrivi pubblico, obiettivo, pagine, esempi, materiali disponibili, tempi e vincoli di budget. Un fornitore serio illustrerà compromessi e possibili fasi; una cifra senza analisi preliminare resta indicativa."] },
      ], relatedServiceSlug: "small-business-web-design",
    },
    pt: {
      slug: "small-business-website-cost-montreal", locale: "pt", ...dates,
      title: "O que influencia o custo de um site para pequenas empresas em Montreal?",
      description: "Os fatores que moldam o custo de um site empresarial em Montreal, sem preços universais nem promessas enganosas.",
      excerpt: "Perceba como âmbito, conteúdo, design, integrações e manutenção influenciam o orçamento.",
      intro: ["Uma estimativa útil começa pelo âmbito, não por um preço genérico. Duas empresas podem pedir cinco páginas e exigir níveis muito diferentes de estratégia, textos, reservas, idiomas e aprovações.", "Compare propostas na mesma base: trabalho incluído, materiais a fornecer, responsabilidades após o lançamento e pressupostos capazes de alterar a estimativa."],
      sections: [
        { heading: "Âmbito e complexidade definem o esforço", paragraphs: ["Um site informativo difere de um projeto com pagamentos, marcações, contas ou catálogo pesquisável. Cada função acrescenta estados de interface, testes, acessibilidade e manutenção. Vários idiomas exigem ainda tradução, navegação e metadados localizados."], checklist: ["Liste as páginas e a ação principal de cada uma.", "Separe o essencial para o lançamento das fases futuras.", "Registe integrações, idiomas e responsáveis pela aprovação."] },
        { heading: "Conteúdo e design alteram a estimativa", paragraphs: ["Uma identidade personalizada, fotografia original e redação profissional levam mais tempo do que materiais finais já aprovados. Confirme se estratégia, edição, imagens, adaptação móvel e rondas de revisão estão incluídas."], checklist: ["Reúna textos, fotografias, logótipos e normas da marca.", "Defina quem escreve, traduz e aprova cada página.", "Esclareça o número de propostas e revisões."] },
        { heading: "Qualidade e propriedade após o lançamento", paragraphs: ["Desempenho, acessibilidade, análise, formulários atentos à privacidade, redirecionamentos e SEO técnico fazem parte de um lançamento sólido. Alojamento, domínio, atualizações e apoio são contínuos."], checklist: ["Confirme a propriedade do domínio, contas e ficheiros-fonte.", "Pergunte por testes, formação, cópias de segurança e apoio.", "Compare entregáveis e exclusões, não apenas o total."] },
        { heading: "Prepare um briefing claro", paragraphs: ["Apresente público, objetivo, páginas, referências, conteúdo existente, prazo e limites de orçamento. Um fornecedor responsável explicará opções e fases. Qualquer valor sem descoberta prévia deve ser tratado como preliminar."] },
      ], relatedServiceSlug: "small-business-web-design",
    },
    zh: {
      slug: "small-business-website-cost-montreal", locale: "zh", ...dates,
      title: "蒙特利尔小企业网站的成本受哪些因素影响？",
      description: "客观梳理蒙特利尔小企业网站预算的影响因素，不提供误导性的一刀切报价或承诺。",
      excerpt: "了解项目范围、内容、设计、功能整合和长期维护如何影响网站预算。",
      intro: ["可靠的估算应从项目范围开始，而不是套用一个通用价格。两家企业即使都需要五个页面，在策略、文案、预约功能、多语言和审批流程上的工作量也可能完全不同。", "比较方案时，应统一标准：包含哪些工作、您需要提供什么、上线后由谁负责，以及哪些前提变化会调整估算。"],
      sections: [
        { heading: "范围与复杂度决定工作量", paragraphs: ["展示型网站与包含付款、预约、会员账户或可筛选目录的网站并不相同。每项功能都会增加界面状态、测试、无障碍和维护工作。多语言发布还需要翻译流程、语言切换及本地化元数据。"], checklist: ["列出每个页面及其最重要的用户行动。", "区分上线必需功能和后续阶段功能。", "写明第三方整合、语言和审批负责人。"] },
        { heading: "内容与设计会改变估算", paragraphs: ["定制视觉系统、原创摄影和专业文案比采用已经定稿的品牌素材需要更多时间。应确认策略、文案编辑、图片选择、响应式设计和修改轮次是否包含在内。"], checklist: ["盘点现有文字、照片、标志及品牌规范。", "明确每页的撰写、翻译和审批负责人。", "确认设计方案及修改轮次。"] },
        { heading: "上线后的质量与所有权", paragraphs: ["性能、无障碍、数据分析、注重隐私的表单、重定向和技术SEO都是可靠上线的一部分。主机、域名、软件更新和支持则是持续责任。"], checklist: ["确认域名、账户、设计及源文件的所有权。", "询问测试、培训、备份和上线后支持。", "按交付内容与排除项比较方案，而非只看总价。"] },
        { heading: "询价前准备清晰需求", paragraphs: ["说明目标客户、业务目标、所需页面、参考网站、现有内容、期限及预算限制。负责任的服务商会解释取舍并建议分阶段实施；未经过需求梳理的数字只能视为初步估算。"] },
      ], relatedServiceSlug: "small-business-web-design",
    },
  },
  "montreal-restaurant-website-checklist": {} as Record<Locale, BlogArticle>,
  "local-seo-checklist-montreal-small-business": {} as Record<Locale, BlogArticle>,
};

type LocalizedDraft = Omit<BlogArticle, "slug" | "locale" | "publishedAt" | "updatedAt" | "author" | "relatedServiceSlug">;

const restaurantDrafts: Record<Locale, LocalizedDraft> = {
  en: { title: "Website checklist for Montreal restaurants and cafés", description: "A practical checklist for restaurant and café websites: menus, mobile usability, local details, reservations, accessibility and measurement.", excerpt: "Help guests find your menu, hours, location and next step quickly—especially on a phone.", intro: ["A restaurant website often has only a few seconds to answer practical questions: Are you open, where are you, what is on the menu and can I reserve or order? The best site removes friction rather than hiding essentials behind decorative effects.", "Use this checklist before a launch or seasonal update. Test it with someone unfamiliar with the business and ask them to find key information without guidance."], sections: [
    { heading: "Make mobile essentials immediate", paragraphs: ["Most urgent restaurant visits begin on a phone. Keep the venue name, cuisine, current hours, address and primary action visible and readable. Avoid PDF-only menus: they are awkward to zoom, harder to update and less accessible."], checklist: ["Publish an HTML menu with prices and dietary notes.", "Make call, directions, reserve and order actions easy to tap.", "Test pages on a small screen and a slower connection."] },
    { heading: "Keep local information consistent", paragraphs: ["Use the same business name, address and phone number on the website and major listings. Explain entrances, accessibility, parking or transit when useful. Special hours should be updated everywhere, not only in a social post."], checklist: ["Show address, map link, phone and current opening hours.", "Add holiday hours and temporary closure notices promptly.", "Check Google Business Profile and other active listings for mismatches."] },
    { heading: "Design reservations and ordering for trust", paragraphs: ["Tell guests whether they will leave your site for a booking or delivery partner. Show relevant policies before confirmation and never make a phone number the only option unless calls are truly the workflow."], checklist: ["Test reservation and ordering links from start to finish.", "Explain deposits, cancellation rules, pickup area and service fees.", "Track completed clicks without collecting unnecessary personal data."] },
    { heading: "Use real, efficient content", paragraphs: ["Current photos of the food, room and storefront help people recognize the experience and location. Compress images, write descriptive alternative text where it adds meaning and remove outdated promotions. Review the site whenever the menu, hours or reservation process changes."] },
  ] },
  fr: { title: "Liste de vérification Web pour restaurants et cafés montréalais", description: "Une liste pratique pour les sites de restaurants et cafés : menus, mobile, informations locales, réservations, accessibilité et mesure.", excerpt: "Aidez les clients à trouver rapidement menu, heures, adresse et prochaine action, surtout sur mobile.", intro: ["Un site de restaurant n’a souvent que quelques secondes pour répondre : êtes-vous ouvert, où êtes-vous, que servez-vous et peut-on réserver ou commander? Un bon site élimine les obstacles au lieu de cacher l’essentiel derrière des effets décoratifs.", "Utilisez cette liste avant un lancement ou une mise à jour saisonnière. Demandez à une personne qui connaît peu l’établissement de trouver les informations sans aide."], sections: [
    { heading: "Rendez l’essentiel immédiat sur mobile", paragraphs: ["Beaucoup de recherches urgentes se font au téléphone. Affichez clairement le nom, le type de cuisine, les heures actuelles, l’adresse et l’action principale. Évitez le menu offert uniquement en PDF, difficile à consulter, à mettre à jour et à rendre accessible."], checklist: ["Publiez un menu HTML avec prix et indications alimentaires.", "Facilitez les appels, itinéraires, réservations et commandes.", "Testez sur petit écran et connexion plus lente."] },
    { heading: "Gardez les renseignements locaux cohérents", paragraphs: ["Utilisez le même nom, la même adresse et le même téléphone sur le site et les principales fiches. Précisez l’entrée, l’accessibilité, le stationnement ou le transport collectif au besoin. Mettez les heures spéciales à jour partout."], checklist: ["Affichez adresse, itinéraire, téléphone et heures actuelles.", "Ajoutez rapidement les heures fériées et fermetures temporaires.", "Repérez les écarts dans la fiche Google et les autres répertoires actifs."] },
    { heading: "Inspirez confiance pour réserver ou commander", paragraphs: ["Dites clairement si le client quitte votre site pour un partenaire. Présentez les politiques utiles avant la confirmation et testez tout le parcours."], checklist: ["Testez chaque lien de réservation et de commande.", "Expliquez dépôts, annulations, zone de cueillette et frais.", "Mesurez les clics utiles sans recueillir de données superflues."] },
    { heading: "Utilisez un contenu réel et léger", paragraphs: ["Des photos actuelles des plats, de la salle et de la façade aident à reconnaître l’expérience. Compressez-les, ajoutez un texte alternatif pertinent et retirez les promotions périmées. Revoyez le site dès que menu, heures ou réservations changent."] },
  ] },
  es: { title: "Lista web para restaurantes y cafeterías de Montreal", description: "Lista práctica para webs gastronómicas: menú, móvil, datos locales, reservas, accesibilidad y medición.", excerpt: "Ayuda a encontrar menú, horario, ubicación y siguiente paso rápidamente, sobre todo desde el móvil.", intro: ["Una web gastronómica dispone de pocos segundos para responder: ¿está abierto, dónde está, qué ofrece y puedo reservar o pedir? Un buen sitio elimina obstáculos en vez de ocultar lo esencial.", "Úsala antes del lanzamiento o de una actualización estacional. Pide a alguien que no conozca el local que encuentre la información sin ayuda."], sections: [
    { heading: "Prioriza lo esencial en el móvil", paragraphs: ["Muchas búsquedas urgentes empiezan en un teléfono. Muestra nombre, tipo de cocina, horario vigente, dirección y acción principal. Evita un menú solo en PDF: cuesta ampliar, actualizar y usar con tecnologías de asistencia."], checklist: ["Publica el menú en HTML con precios y notas alimentarias.", "Facilita llamar, llegar, reservar y pedir.", "Prueba con pantalla pequeña y conexión lenta."] },
    { heading: "Mantén coherentes los datos locales", paragraphs: ["Usa el mismo nombre, dirección y teléfono en la web y los directorios. Explica acceso, estacionamiento o transporte cuando ayude. Actualiza horarios especiales en todos los canales."], checklist: ["Muestra dirección, ruta, teléfono y horario actual.", "Añade festivos y cierres temporales rápidamente.", "Compara Google Business Profile con otros listados activos."] },
    { heading: "Genera confianza al reservar y pedir", paragraphs: ["Avisa si el usuario pasará a un socio externo. Presenta políticas relevantes antes de confirmar y prueba todo el recorrido."], checklist: ["Prueba enlaces de reserva y pedido de principio a fin.", "Explica depósitos, cancelaciones, recogida y cargos.", "Mide clics completados sin recopilar datos innecesarios."] },
    { heading: "Usa contenido real y eficiente", paragraphs: ["Fotos actuales de platos, sala y fachada ayudan a reconocer el lugar. Comprime imágenes, añade texto alternativo útil y elimina promociones antiguas. Revisa la web cuando cambien menú, horario o reservas."] },
  ] },
  de: { title: "Website-Checkliste für Restaurants und Cafés in Montreal", description: "Praktische Checkliste zu Speisekarte, mobiler Nutzung, Standortdaten, Reservierung, Barrierefreiheit und Messung.", excerpt: "Gäste sollen Speisekarte, Öffnungszeiten, Standort und nächsten Schritt schnell finden.", intro: ["Eine Restaurant-Website hat oft nur Sekunden, um Fragen zu beantworten: Ist geöffnet, wo liegt das Lokal, was gibt es und kann ich reservieren oder bestellen? Eine gute Website beseitigt Hürden.", "Nutzen Sie die Liste vor dem Start oder einem saisonalen Update. Lassen Sie eine ortsfremde Person wichtige Informationen ohne Hilfe suchen."], sections: [
    { heading: "Mobiles Wesentliches sofort zeigen", paragraphs: ["Viele dringende Restaurant-Suchen beginnen am Smartphone. Name, Küche, aktuelle Zeiten, Adresse und Hauptaktion müssen gut lesbar sein. Vermeiden Sie reine PDF-Speisekarten; sie sind umständlich, schwerer zu pflegen und weniger barrierefrei."], checklist: ["HTML-Speisekarte mit Preisen und Ernährungshinweisen anbieten.", "Anruf, Route, Reservierung und Bestellung leicht antippbar machen.", "Auf kleinem Display und langsamer Verbindung testen."] },
    { heading: "Lokale Angaben konsistent halten", paragraphs: ["Verwenden Sie auf Website und Verzeichnissen denselben Namen, dieselbe Adresse und Telefonnummer. Erklären Sie Eingang, Zugänglichkeit, Parken oder Nahverkehr. Sonderzeiten müssen überall aktualisiert werden."], checklist: ["Adresse, Routenlink, Telefon und aktuelle Zeiten zeigen.", "Feiertagszeiten und vorübergehende Schließungen zeitnah ergänzen.", "Google-Unternehmensprofil und aktive Verzeichnisse abgleichen."] },
    { heading: "Vertrauen bei Reservierung und Bestellung", paragraphs: ["Kennzeichnen Sie den Wechsel zu einem externen Anbieter. Zeigen Sie wichtige Regeln vor der Bestätigung und testen Sie den gesamten Ablauf."], checklist: ["Reservierungs- und Bestelllinks vollständig testen.", "Anzahlung, Stornierung, Abholung und Gebühren erklären.", "Abgeschlossene Klicks ohne unnötige Personendaten messen."] },
    { heading: "Echte und effiziente Inhalte nutzen", paragraphs: ["Aktuelle Bilder von Speisen, Raum und Fassade vermitteln die Erfahrung. Komprimieren Sie Bilder, verfassen Sie sinnvolle Alternativtexte und entfernen Sie alte Aktionen. Aktualisieren Sie die Website bei jeder Änderung von Karte, Zeiten oder Buchung."] },
  ] },
  it: { title: "Checklist per siti di ristoranti e caffè di Montréal", description: "Una lista pratica per menu, mobile, informazioni locali, prenotazioni, accessibilità e misurazione.", excerpt: "Aiuta gli ospiti a trovare rapidamente menu, orari, indirizzo e prossima azione, soprattutto da mobile.", intro: ["Il sito di un locale ha pochi secondi per rispondere: siete aperti, dove siete, cosa servite e posso prenotare o ordinare? Un buon sito elimina gli ostacoli invece di nascondere l’essenziale.", "Usa questa lista prima del lancio o di un aggiornamento stagionale. Chiedi a chi non conosce il locale di trovare le informazioni senza assistenza."], sections: [
    { heading: "Rendi immediato l’essenziale su mobile", paragraphs: ["Molte ricerche urgenti partono dal telefono. Mostra nome, cucina, orari attuali, indirizzo e azione principale. Evita menu solo in PDF, scomodi da ingrandire, aggiornare e usare con tecnologie assistive."], checklist: ["Pubblica un menu HTML con prezzi e note alimentari.", "Semplifica chiamate, indicazioni, prenotazioni e ordini.", "Prova su schermo piccolo e connessione lenta."] },
    { heading: "Mantieni coerenti le informazioni locali", paragraphs: ["Usa gli stessi nome, indirizzo e telefono sul sito e nelle directory. Spiega ingresso, accessibilità, parcheggio o trasporti quando utile. Aggiorna ovunque gli orari speciali."], checklist: ["Mostra indirizzo, percorso, telefono e orari correnti.", "Aggiungi subito festività e chiusure temporanee.", "Confronta Profilo dell’attività Google e directory attive."] },
    { heading: "Crea fiducia in prenotazioni e ordini", paragraphs: ["Avvisa se l’utente passerà a un servizio esterno. Mostra le condizioni pertinenti prima della conferma e verifica tutto il percorso."], checklist: ["Prova i link di prenotazione e ordine fino alla fine.", "Spiega depositi, cancellazioni, ritiro e costi.", "Misura i clic completati senza dati personali superflui."] },
    { heading: "Usa contenuti reali ed efficienti", paragraphs: ["Foto recenti di piatti, sala e facciata aiutano a riconoscere il luogo. Comprimi le immagini, usa testi alternativi utili e rimuovi promozioni scadute. Aggiorna il sito quando cambiano menu, orari o prenotazioni."] },
  ] },
  pt: { title: "Lista para sites de restaurantes e cafés de Montreal", description: "Lista prática para menu, utilização móvel, dados locais, reservas, acessibilidade e medição.", excerpt: "Ajude clientes a encontrar menu, horário, localização e próxima ação rapidamente, sobretudo no telemóvel.", intro: ["Um site de restauração tem poucos segundos para responder: está aberto, onde fica, o que serve e posso reservar ou pedir? Um bom site remove obstáculos em vez de esconder o essencial.", "Use esta lista antes do lançamento ou de uma atualização sazonal. Peça a alguém que não conheça o espaço para encontrar informações sem ajuda."], sections: [
    { heading: "Dê prioridade ao essencial no telemóvel", paragraphs: ["Muitas pesquisas urgentes começam num telefone. Mostre nome, cozinha, horários atuais, morada e ação principal. Evite menus apenas em PDF: são difíceis de ampliar, atualizar e usar com tecnologia assistiva."], checklist: ["Publique um menu HTML com preços e notas alimentares.", "Facilite chamadas, direções, reservas e pedidos.", "Teste num ecrã pequeno e ligação lenta."] },
    { heading: "Mantenha os dados locais consistentes", paragraphs: ["Use o mesmo nome, morada e telefone no site e diretórios. Explique entrada, acessibilidade, estacionamento ou transportes quando necessário. Atualize horários especiais em todo o lado."], checklist: ["Mostre morada, rota, telefone e horários atuais.", "Adicione feriados e fechos temporários prontamente.", "Compare o Perfil da Empresa no Google com diretórios ativos."] },
    { heading: "Crie confiança nas reservas e pedidos", paragraphs: ["Avise quando a pessoa passar para um parceiro externo. Mostre políticas relevantes antes da confirmação e teste todo o percurso."], checklist: ["Teste links de reserva e pedido até ao fim.", "Explique depósitos, cancelamentos, recolha e taxas.", "Meça cliques concluídos sem recolher dados desnecessários."] },
    { heading: "Use conteúdo real e eficiente", paragraphs: ["Fotografias atuais dos pratos, sala e fachada ajudam a reconhecer a experiência. Comprima imagens, escreva texto alternativo útil e retire promoções antigas. Reveja o site sempre que menu, horários ou reservas mudarem."] },
  ] },
  zh: { title: "蒙特利尔餐厅与咖啡馆网站检查清单", description: "涵盖菜单、移动体验、本地信息、预订、无障碍和效果衡量的实用网站清单。", excerpt: "让顾客尤其是在手机上，迅速找到菜单、营业时间、位置和下一步操作。", intro: ["餐饮网站通常只有几秒钟回答顾客的实际问题：现在营业吗、在哪里、供应什么、能否预订或点餐？优秀的网站应减少阻力，而不是用装饰效果隐藏关键信息。", "在上线或季节性更新前使用这份清单。请一位不熟悉店铺的人在无人提示下寻找重点信息，更容易发现问题。"], sections: [
    { heading: "移动端首先展示核心信息", paragraphs: ["许多即时餐饮搜索来自手机。店名、菜系、当前营业时间、地址和主要行动按钮应清晰可读。不要只提供PDF菜单；它不便缩放、更新，也不利于无障碍访问。"], checklist: ["提供包含价格和饮食说明的HTML菜单。", "让电话、导航、预订和点餐按钮易于点击。", "在小屏幕和较慢网络下完整测试。"] },
    { heading: "保持本地信息一致", paragraphs: ["网站与主要商家目录应使用完全一致的名称、地址和电话。必要时说明入口、无障碍设施、停车或公共交通。特殊营业时间必须在所有渠道同步。"], checklist: ["显示地址、导航链接、电话和当前营业时间。", "及时添加节假日时间和临时停业通知。", "核对Google商家资料与其他有效目录。"] },
    { heading: "让预订和点餐建立信任", paragraphs: ["如果顾客将跳转到第三方平台，应提前说明。确认前展示适用政策，并完整测试流程。"], checklist: ["从头到尾测试预订及点餐链接。", "说明订金、取消、取餐区域及服务费用。", "衡量完成点击，但不收集不必要的个人资料。"] },
    { heading: "使用真实且高效的内容", paragraphs: ["近期的菜品、室内和门面照片能帮助顾客了解并找到店铺。压缩图片，在有意义时添加替代文字，并移除过期促销。菜单、时间或预订方式改变后应立即检查网站。"] },
  ] },
};

const seoDrafts: Record<Locale, LocalizedDraft> = {
  en: { title: "A practical local SEO checklist for Montreal small businesses", description: "A realistic local SEO checklist covering website foundations, Google Business Profile, reviews, local relevance and measurement.", excerpt: "Build accurate, useful local signals that help customers discover and evaluate your Montreal business.", intro: ["Local SEO makes a business easier to discover and evaluate when people search in a geographic context. It is not a one-time trick and no checklist can guarantee a position: proximity, relevance, prominence, competition and search context all influence results.", "Focus first on accurate information and a genuinely useful customer experience. Then measure enquiries, calls, bookings and direction requests—not rankings alone."], sections: [
    { heading: "Fix website foundations", paragraphs: ["Create a clear page for each real service or location that deserves distinct information. Use descriptive titles and headings, make contact details easy to verify and ensure pages work quickly on mobile. Do not produce near-duplicate neighbourhood pages with only the place name changed."], checklist: ["Confirm indexable pages, self canonicals and working internal links.", "Place consistent business details and service-area information where helpful.", "Add relevant structured data without marking up claims users cannot see."] },
    { heading: "Maintain your Google Business Profile", paragraphs: ["Choose the most accurate primary category, complete services and attributes, and keep regular and special hours current. Use real photos. Businesses serving customers at their location should place the map pin correctly; service-area businesses must follow platform rules about address visibility."], checklist: ["Verify name, category, phone, website, address or service area.", "Review hours, appointment links, photos and outdated fields monthly.", "Use tracking parameters carefully so website visits remain measurable."] },
    { heading: "Earn trust through reviews and local evidence", paragraphs: ["Ask real customers for honest feedback at a natural point after service. Never buy, gate or script reviews. Respond helpfully without exposing private details. Local partnerships, associations, media coverage and useful community resources can reinforce relevance when they are genuine."], checklist: ["Create a simple, policy-compliant review request process.", "Reply to positive and critical reviews professionally.", "Correct inconsistent listings and pursue relevant local mentions."] },
    { heading: "Measure outcomes and improve", paragraphs: ["Connect analytics and search performance tools, respecting consent and privacy requirements. Record a baseline, annotate major changes and review trends over meaningful periods. Search results fluctuate, so combine visibility data with qualified leads and revenue-related actions."], checklist: ["Track form completions, calls, bookings and direction clicks.", "Review queries and landing pages for unmet customer questions.", "Update weak content and technical issues before publishing more pages."] },
  ] },
  fr: { title: "Liste SEO local pratique pour les PME de Montréal", description: "Une liste réaliste couvrant le site, la fiche Google, les avis, la pertinence locale et la mesure.", excerpt: "Créez des signaux locaux exacts et utiles pour aider les clients à découvrir et évaluer votre entreprise.", intro: ["Le SEO local aide une entreprise à être découverte et évaluée lors de recherches géographiques. Ce n’est pas une astuce ponctuelle et aucune liste ne garantit une position : proximité, pertinence, notoriété, concurrence et contexte influencent les résultats.", "Commencez par des renseignements exacts et une expérience réellement utile. Mesurez ensuite demandes, appels, réservations et itinéraires, pas seulement les positions."], sections: [
    { heading: "Solidifiez les bases du site", paragraphs: ["Créez une page claire pour chaque vrai service ou emplacement qui mérite une information distincte. Soignez titres, rubriques, coordonnées et vitesse mobile. Évitez les pages de quartiers presque identiques où seul le lieu change."], checklist: ["Vérifiez indexation, canoniques autonomes et liens internes.", "Affichez des renseignements cohérents sur l’entreprise et la zone desservie.", "Ajoutez des données structurées uniquement pour le contenu visible."] },
    { heading: "Entretenez votre fiche d’entreprise Google", paragraphs: ["Choisissez la catégorie principale la plus précise, complétez services et attributs, puis gardez les heures régulières et spéciales à jour. Utilisez de vraies photos et respectez les règles d’affichage de l’adresse pour les entreprises de zone de service."], checklist: ["Validez nom, catégorie, téléphone, site, adresse ou zone.", "Revoyez chaque mois heures, liens, photos et champs périmés.", "Utilisez des paramètres de suivi sans nuire à l’adresse finale."] },
    { heading: "Développez la confiance avec des preuves locales", paragraphs: ["Demandez un avis honnête aux vrais clients au bon moment. N’achetez pas d’avis et ne filtrez pas les demandes. Répondez sans révéler d’information privée. Partenariats, associations et médias locaux sont utiles lorsqu’ils sont authentiques."], checklist: ["Créez une demande d’avis simple et conforme.", "Répondez professionnellement aux avis positifs et critiques.", "Corrigez les fiches incohérentes et cherchez des mentions pertinentes."] },
    { heading: "Mesurez les résultats et améliorez", paragraphs: ["Reliez outils d’analytique et de recherche en respectant consentement et vie privée. Établissez une référence, notez les changements et étudiez les tendances sur une période significative."], checklist: ["Mesurez formulaires, appels, réservations et itinéraires.", "Repérez dans les requêtes les questions encore sans réponse.", "Améliorez les pages faibles et problèmes techniques avant d’en ajouter."] },
  ] },
  es: { title: "Lista práctica de SEO local para pequeñas empresas de Montreal", description: "Lista realista sobre web, Perfil de Empresa de Google, reseñas, relevancia local y medición.", excerpt: "Crea señales locales precisas y útiles que ayuden a descubrir y evaluar tu negocio.", intro: ["El SEO local facilita descubrir y evaluar un negocio en búsquedas geográficas. No es un truco único y ninguna lista garantiza posiciones: proximidad, relevancia, popularidad, competencia y contexto influyen en los resultados.", "Prioriza información exacta y una experiencia útil. Después mide consultas, llamadas, reservas y solicitudes de ruta, no solo rankings."], sections: [
    { heading: "Corrige las bases de la web", paragraphs: ["Crea una página clara para cada servicio o ubicación real que necesite información propia. Usa títulos descriptivos, datos verificables y buen rendimiento móvil. Evita páginas casi duplicadas que solo cambian el barrio."], checklist: ["Comprueba indexación, canónicas propias y enlaces internos.", "Muestra datos coherentes y zona de servicio cuando sea útil.", "Añade datos estructurados solo sobre contenido visible."] },
    { heading: "Mantén el Perfil de Empresa de Google", paragraphs: ["Elige la categoría principal más precisa, completa servicios y atributos y actualiza horarios normales y especiales. Usa fotos reales y respeta las reglas para mostrar direcciones de negocios con área de servicio."], checklist: ["Verifica nombre, categoría, teléfono, web, dirección o área.", "Revisa cada mes horarios, enlaces, fotos y campos antiguos.", "Usa parámetros de seguimiento con cuidado."] },
    { heading: "Gana confianza con reseñas y evidencia local", paragraphs: ["Pide opiniones honestas a clientes reales en un momento natural. No compres, filtres ni escribas reseñas. Responde sin revelar datos privados. Las alianzas, asociaciones y menciones locales ayudan cuando son auténticas."], checklist: ["Crea un proceso sencillo y conforme para pedir reseñas.", "Responde profesionalmente a comentarios positivos y críticos.", "Corrige directorios incoherentes y busca menciones pertinentes."] },
    { heading: "Mide resultados y mejora", paragraphs: ["Conecta analítica y herramientas de búsqueda respetando consentimiento y privacidad. Registra una base, anota cambios y revisa tendencias durante periodos significativos."], checklist: ["Mide formularios, llamadas, reservas y solicitudes de ruta.", "Busca preguntas sin responder en consultas y páginas de entrada.", "Mejora contenido débil y errores técnicos antes de publicar más."] },
  ] },
  de: { title: "Praktische lokale SEO-Checkliste für Kleinunternehmen in Montreal", description: "Realistische Checkliste zu Website, Google-Unternehmensprofil, Bewertungen, lokaler Relevanz und Messung.", excerpt: "Schaffen Sie korrekte lokale Signale, mit denen Kunden Ihr Unternehmen entdecken und bewerten können.", intro: ["Lokale SEO erleichtert das Finden und Einschätzen eines Unternehmens bei geografischen Suchen. Sie ist kein einmaliger Trick, und keine Checkliste garantiert eine Position: Nähe, Relevanz, Bekanntheit, Wettbewerb und Kontext wirken zusammen.", "Konzentrieren Sie sich zuerst auf korrekte Angaben und echten Kundennutzen. Messen Sie danach Anfragen, Anrufe, Buchungen und Routenaufrufe – nicht nur Rankings."], sections: [
    { heading: "Website-Grundlagen ordnen", paragraphs: ["Erstellen Sie klare Seiten für echte Leistungen oder Standorte mit eigenständigen Informationen. Nutzen Sie aussagekräftige Titel, überprüfbare Kontaktdaten und schnelle mobile Seiten. Vermeiden Sie nahezu identische Stadtteilseiten."], checklist: ["Indexierbarkeit, selbstreferenzielle Canonicals und interne Links prüfen.", "Einheitliche Unternehmens- und Einzugsgebietsangaben zeigen.", "Strukturierte Daten nur für sichtbare Aussagen einsetzen."] },
    { heading: "Google-Unternehmensprofil pflegen", paragraphs: ["Wählen Sie die genaueste Hauptkategorie, ergänzen Sie Leistungen und Attribute und halten Sie reguläre sowie besondere Zeiten aktuell. Nutzen Sie echte Fotos und beachten Sie Regeln zur Adressanzeige für Einzugsgebiete."], checklist: ["Name, Kategorie, Telefon, Website, Adresse oder Gebiet prüfen.", "Zeiten, Links, Fotos und alte Felder monatlich kontrollieren.", "Tracking-Parameter sorgfältig verwenden."] },
    { heading: "Vertrauen durch Bewertungen und lokale Belege", paragraphs: ["Bitten Sie echte Kunden zum passenden Zeitpunkt um ehrliches Feedback. Kaufen, filtern oder formulieren Sie keine Bewertungen. Antworten Sie ohne private Details. Lokale Partnerschaften und Mediennennungen helfen, wenn sie echt sind."], checklist: ["Einfachen, richtlinienkonformen Bewertungsprozess schaffen.", "Auf Lob und Kritik professionell antworten.", "Uneinheitliche Verzeichnisse korrigieren und relevante Erwähnungen fördern."] },
    { heading: "Ergebnisse messen und verbessern", paragraphs: ["Verbinden Sie Analytics- und Suchtools unter Beachtung von Einwilligung und Datenschutz. Halten Sie Ausgangswerte und Änderungen fest und bewerten Sie Trends über sinnvolle Zeiträume."], checklist: ["Formulare, Anrufe, Buchungen und Routenaufrufe messen.", "Suchanfragen auf offene Kundenfragen prüfen.", "Schwache Inhalte und technische Probleme vor neuen Seiten verbessern."] },
  ] },
  it: { title: "Checklist SEO locale pratica per piccole imprese di Montréal", description: "Una lista realistica su sito, Profilo dell’attività Google, recensioni, pertinenza locale e misurazione.", excerpt: "Crea segnali locali accurati e utili che aiutino i clienti a trovare e valutare la tua attività.", intro: ["La SEO locale rende un’attività più facile da trovare e valutare nelle ricerche geografiche. Non è un trucco isolato e nessuna lista garantisce una posizione: distanza, pertinenza, notorietà, concorrenza e contesto incidono sui risultati.", "Parti da informazioni corrette e da un’esperienza davvero utile. Misura poi richieste, chiamate, prenotazioni e indicazioni stradali, non solo le posizioni."], sections: [
    { heading: "Sistema le basi del sito", paragraphs: ["Crea una pagina chiara per ogni servizio o sede reale che richieda informazioni distinte. Usa titoli descrittivi, contatti verificabili e pagine mobili veloci. Evita pagine di quartiere quasi duplicate."], checklist: ["Controlla indicizzazione, canonical autonome e link interni.", "Mostra dati aziendali e area servita in modo coerente.", "Aggiungi dati strutturati solo per informazioni visibili."] },
    { heading: "Mantieni il Profilo dell’attività Google", paragraphs: ["Scegli la categoria principale più precisa, completa servizi e attributi e aggiorna orari normali e speciali. Usa foto reali e rispetta le regole sull’indirizzo per le attività che operano a domicilio."], checklist: ["Verifica nome, categoria, telefono, sito, indirizzo o area.", "Rivedi ogni mese orari, link, foto e campi obsoleti.", "Usa con attenzione i parametri di tracciamento."] },
    { heading: "Costruisci fiducia con recensioni e prove locali", paragraphs: ["Chiedi feedback onesti a clienti reali nel momento giusto. Non acquistare, filtrare o scrivere recensioni. Rispondi senza esporre dettagli privati. Collaborazioni e citazioni locali aiutano quando sono autentiche."], checklist: ["Crea una richiesta di recensione semplice e conforme.", "Rispondi professionalmente a elogi e critiche.", "Correggi directory incoerenti e cerca citazioni pertinenti."] },
    { heading: "Misura e migliora", paragraphs: ["Collega analytics e strumenti di ricerca rispettando consenso e privacy. Registra un riferimento iniziale, annota i cambiamenti e valuta tendenze su periodi significativi."], checklist: ["Misura moduli, chiamate, prenotazioni e richieste di percorso.", "Trova domande senza risposta nelle query e pagine di ingresso.", "Migliora contenuti deboli e problemi tecnici prima di pubblicare altro."] },
  ] },
  pt: { title: "Lista prática de SEO local para pequenas empresas de Montreal", description: "Uma lista realista sobre site, Perfil da Empresa no Google, avaliações, relevância local e medição.", excerpt: "Crie sinais locais exatos e úteis que ajudem clientes a descobrir e avaliar a sua empresa.", intro: ["O SEO local facilita a descoberta e avaliação de uma empresa em pesquisas geográficas. Não é um truque único e nenhuma lista garante posições: proximidade, relevância, notoriedade, concorrência e contexto influenciam resultados.", "Comece por informação correta e uma experiência realmente útil. Depois meça contactos, chamadas, reservas e pedidos de direções, não apenas classificações."], sections: [
    { heading: "Corrija as bases do site", paragraphs: ["Crie uma página clara para cada serviço ou localização real que mereça informação própria. Use títulos descritivos, contactos verificáveis e bom desempenho móvel. Evite páginas de bairros quase duplicadas."], checklist: ["Verifique indexação, canónicas próprias e ligações internas.", "Mostre dados consistentes e área de serviço quando útil.", "Adicione dados estruturados apenas sobre conteúdo visível."] },
    { heading: "Mantenha o Perfil da Empresa no Google", paragraphs: ["Escolha a categoria principal mais exata, complete serviços e atributos e atualize horários normais e especiais. Use fotografias reais e siga as regras de morada para empresas de área de serviço."], checklist: ["Confirme nome, categoria, telefone, site, morada ou área.", "Reveja mensalmente horários, links, fotos e campos antigos.", "Use parâmetros de acompanhamento com cuidado."] },
    { heading: "Crie confiança com avaliações e provas locais", paragraphs: ["Peça opiniões honestas a clientes reais no momento adequado. Não compre, filtre nem escreva avaliações. Responda sem revelar dados privados. Parcerias e menções locais ajudam quando são genuínas."], checklist: ["Crie um processo simples e compatível para pedir avaliações.", "Responda profissionalmente a elogios e críticas.", "Corrija diretórios inconsistentes e procure menções relevantes."] },
    { heading: "Meça resultados e melhore", paragraphs: ["Ligue análise e ferramentas de pesquisa respeitando consentimento e privacidade. Registe uma base, anote alterações e analise tendências em períodos significativos."], checklist: ["Meça formulários, chamadas, reservas e pedidos de direções.", "Procure perguntas por responder nas consultas e páginas de entrada.", "Melhore conteúdo fraco e problemas técnicos antes de publicar mais."] },
  ] },
  zh: { title: "蒙特利尔小企业实用本地SEO检查清单", description: "涵盖网站基础、Google商家资料、评价、本地相关性及效果衡量的务实SEO清单。", excerpt: "建立准确、有用的本地信号，帮助客户发现并评估您的蒙特利尔业务。", intro: ["本地SEO让企业在带有地理意图的搜索中更容易被发现和评估。它不是一次性技巧，任何清单也无法保证排名；距离、相关性、知名度、竞争和搜索情境都会影响结果。", "首先确保资料准确，并提供真正有用的客户体验。然后衡量咨询、电话、预订和导航请求，而不只是排名。"], sections: [
    { heading: "打好网站基础", paragraphs: ["为每项真实服务或确实需要独立信息的地点建立清晰页面。使用描述性标题，提供易于核实的联系方式，并确保移动端速度。不要大量制作只替换地区名称的重复页面。"], checklist: ["检查页面可索引、自引用canonical及内部链接。", "在有帮助的位置显示一致的企业与服务区域资料。", "结构化数据只标记用户实际可见的内容。"] },
    { heading: "维护Google商家资料", paragraphs: ["选择最准确的主要类别，完整填写服务和属性，并及时更新常规与特殊营业时间。使用真实照片；上门服务型企业应遵守地址显示及服务区域规则。"], checklist: ["核对名称、类别、电话、网站、地址或服务区域。", "每月检查营业时间、预约链接、照片和过期资料。", "谨慎使用追踪参数，确保网站访问可衡量。"] },
    { heading: "通过评价和本地证据建立信任", paragraphs: ["在服务完成后的自然时机邀请真实客户留下诚实反馈。不要购买、筛选或代写评价。回复时避免泄露私人资料。真实的本地合作、协会和媒体报道也能增强相关性。"], checklist: ["建立简单且符合平台政策的评价邀请流程。", "专业回复正面及批评性评价。", "修正不一致的目录信息，争取相关本地提及。"] },
    { heading: "衡量结果并持续改善", paragraphs: ["在符合用户同意和隐私要求的前提下连接分析及搜索工具。记录基准与重大变更，并在有意义的周期内观察趋势。"], checklist: ["追踪表单、电话、预订和导航点击。", "从搜索查询和落地页中寻找未回答的问题。", "先改善薄弱内容与技术问题，再增加新页面。"] },
  ] },
};

for (const locale of Object.keys(restaurantDrafts) as Locale[]) {
  articles["montreal-restaurant-website-checklist"][locale] = {
    slug: "montreal-restaurant-website-checklist", locale, ...dates,
    ...restaurantDrafts[locale], relatedServiceSlug: "restaurant-website-design",
  };
  articles["local-seo-checklist-montreal-small-business"][locale] = {
    slug: "local-seo-checklist-montreal-small-business", locale, ...dates,
    ...seoDrafts[locale], relatedServiceSlug: "small-business-web-design",
  };
}

export function getBlogArticle(slug: string, locale: Locale): BlogArticle | undefined {
  if (!blogSlugs.includes(slug as BlogSlug)) return undefined;
  return articles[slug as BlogSlug][locale];
}

export function getBlogArticles(locale: Locale): BlogArticle[] {
  return blogSlugs.map((slug) => articles[slug][locale]);
}
