import type { Locale } from "@/lib/i18n";

type Step = { title: string; description: string };
type Value = { title: string; description: string };
type ProjectOption = { value: string; label: string };

export type PageTranslations = {
  nav: {
    home: string;
    about: string;
    services: string;
    blog: string;
    contact: string;
    startProject: string;
    primaryLabel: string;
    mobileLabel: string;
    openMenu: string;
    closeMenu: string;
    homeLabel: string;
    languageLabel: string;
  };
  footer: {
    description: string;
    pages: string;
    services: string;
    getInTouch: string;
    location: string;
    serviceArea: string;
    copyright: string;
    serviceTitles: Record<string, string>;
  };
  home: {
    eyebrow: string;
    title: string;
    titleAccent: string;
    intro: string;
    primaryCta: string;
    secondaryCta: string;
    imageAlt: string;
    processEyebrow: string;
    processTitle: string;
    steps: Step[];
    ctaTitle: string;
    ctaText: string;
    ctaButton: string;
  };
  about: {
    eyebrow: string;
    title: string;
    titleAccent: string;
    intro: string;
    statLabels: [string, string, string, string];
    storyTitle: string;
    storyTitleAccent: string;
    storyParagraphs: [string, string];
    imageAlt: string;
    valuesEyebrow: string;
    valuesTitle: string;
    values: Value[];
    ctaTitle: string;
    ctaAccent: string;
    ctaButton: string;
  };
  contact: {
    eyebrow: string;
    title: string;
    titleAccent: string;
    intro: string;
    directTitle: string;
    directText: string;
    phone: string;
    email: string;
    serviceArea: string;
    serviceAreaValue: string;
    experience: string;
    formTitle: string;
    name: string;
    emailPlaceholder: string;
    phonePlaceholder: string;
    projectType: string;
    projectOptions: ProjectOption[];
    details: string;
    sending: string;
    send: string;
    success: string;
    genericError: string;
    errorFallback: string;
  };
  metadata: {
    homeTitle: string;
    homeDescription: string;
    aboutTitle: string;
    aboutDescription: string;
    contactTitle: string;
    contactDescription: string;
  };
};

const serviceValues = [
  "Business Website",
  "E-commerce Store",
  "Restaurant / Café",
  "Advertising / Landing Page",
  "Mobile Application",
  "Custom Software",
  "Something Else",
] as const;

function options(labels: readonly string[]): ProjectOption[] {
  return serviceValues.map((value, index) => ({ value, label: labels[index] }));
}

export const pageTranslations: Record<Locale, PageTranslations> = {
  en: {
    nav: { home: "Home", about: "About", services: "Services", blog: "Blog", contact: "Contact", startProject: "Start a Project", primaryLabel: "Primary navigation", mobileLabel: "Mobile navigation", openMenu: "Open menu", closeMenu: "Close menu", homeLabel: "Arash Web Studio home", languageLabel: "Language" },
    footer: {
      description: "Founded and led by Arash Ammarlooi in Montreal. Independent web design, e-commerce, apps and custom software for businesses in Canada and worldwide.",
      pages: "Pages", services: "Services", getInTouch: "Get in touch", location: "Montreal, Quebec", serviceArea: "Serving Canada and clients worldwide", copyright: "Founded and led by Arash Ammarlooi.",
      serviceTitles: { "ecommerce-web-design": "E-commerce Website Design", "restaurant-website-design": "Restaurant & Café Website Design", "small-business-web-design": "Small Business Web Design", "mobile-app-design": "Mobile Application Design", "custom-software-development": "Custom Software Development", "brand-identity-design": "Brand & Visual Identity Design" },
    },
    home: {
      eyebrow: "Web · Mobile · Software", title: "We design your website,", titleAccent: "your way.", intro: "Montreal web design and development for businesses in Quebec, across Canada and worldwide. We create e-commerce stores, restaurant and café websites, landing pages, mobile apps and custom software.", primaryCta: "Start Your Project", secondaryCta: "About Arash", imageAlt: "Responsive website design displayed on a phone and laptop", processEyebrow: "How it works", processTitle: "From idea to launch",
      steps: [{ title: "Discover", description: "We listen to your vision, your business and your goals." }, { title: "Design", description: "Clean concepts crafted around your brand and audience." }, { title: "Build", description: "Careful development for web, mobile and software." }, { title: "Launch", description: "We ship, optimize and support your product worldwide." }],
      ctaTitle: "Ready to build something great?", ctaText: "Tell us about your business and we'll design a website, app or platform that makes it shine.", ctaButton: "Let's Talk",
    },
    about: {
      eyebrow: "About us", title: "Independent studio.", titleAccent: "Personal service.", intro: "Arash Ammarlooi founded and leads this independent Montreal web studio. Since 2013, the studio has designed and built digital experiences for clients in Canada and across the world.", statLabels: ["Years of experience", "Projects delivered", "Countries reached", "Passion for design"], storyTitle: "Led by Arash, built around", storyTitleAccent: "your goals", storyParagraphs: ["Arash Ammarlooi is the founder and lead designer behind Arash Web Studio in Montreal, Quebec. Every client works directly with him from the first conversation through launch. For projects that need additional expertise, he collaborates with trusted independent designers and developers.", "Working across countries and cultures taught us something valuable: great design is universal, but great service is personal. No matter where you are or what your business is, we design around you — your customers, your market, your vision."], imageAlt: "Globe representing clients served in Montreal, Canada and worldwide", valuesEyebrow: "What drives us", valuesTitle: "Our values",
      values: [{ title: "Flexible Collaboration", description: "Arash leads every project and brings in trusted independent designers or developers when a project needs additional expertise." }, { title: "Craft Over Everything", description: "Thirteen years of refining our craft means every pixel, every animation and every interaction is intentional." }, { title: "Business-First Thinking", description: "Beautiful is not enough. Every project is designed to grow your business — more customers, more sales, more impact." }, { title: "True Partnership", description: "From the first sketch to long after launch, we work side by side with you. Your goals become our goals." }],
      ctaTitle: "Want personal service backed by", ctaAccent: "real experience?", ctaButton: "Get in Touch",
    },
    contact: {
      eyebrow: "Contact", title: "Let's make something", titleAccent: "great.", intro: "Tell Arash Ammarlooi about your project — a website, an online store, an app or anything in between. You'll usually receive a reply within 24 hours.", directTitle: "Direct contact", directText: "Work directly with Arash from the first conversation. Call, text or email to discuss your project.", phone: "Phone", email: "Email", serviceArea: "Service area", serviceAreaValue: "Montreal, Quebec · Canada and worldwide", experience: "13+ years of experience · projects delivered in 14 countries.", formTitle: "Start your project", name: "Your name", emailPlaceholder: "Your email", phonePlaceholder: "Phone (optional)", projectType: "Project type", projectOptions: options(serviceValues), details: "Tell us about your project", sending: "Sending...", send: "Send Message", success: "Message sent! We'll get back to you within 24 hours.", genericError: "Something went wrong.", errorFallback: "You can also email us directly at",
    },
    metadata: { homeTitle: "Montreal Web Design | Arash Web Studio", homeDescription: "Montreal web designer creating websites, e-commerce stores, mobile apps and custom software for businesses in Quebec, across Canada and worldwide.", aboutTitle: "About Arash Ammarlooi", aboutDescription: "Meet Arash Ammarlooi, founder and lead designer at Arash Web Studio in Montreal, and learn about his collaborative approach to digital projects.", contactTitle: "Contact a Montreal Web Designer", contactDescription: "Contact Arash Ammarlooi, a Montreal web designer, to discuss a business website, e-commerce store, mobile app or custom software project." },
  },
  fr: {
    nav: { home: "Accueil", about: "À propos", services: "Services", blog: "Blogue", contact: "Contact", startProject: "Démarrer un projet", primaryLabel: "Navigation principale", mobileLabel: "Navigation mobile", openMenu: "Ouvrir le menu", closeMenu: "Fermer le menu", homeLabel: "Accueil d’Arash Web Studio", languageLabel: "Langue" },
    footer: { description: "Fondé et dirigé par Arash Ammarlooi à Montréal. Studio indépendant de conception web, commerce électronique, applications et logiciels sur mesure pour les entreprises au Canada et ailleurs dans le monde.", pages: "Pages", services: "Services", getInTouch: "Nous joindre", location: "Montréal, Québec", serviceArea: "Au service du Canada et de clients du monde entier", copyright: "Fondé et dirigé par Arash Ammarlooi.", serviceTitles: { "ecommerce-web-design": "Conception de sites de commerce électronique", "restaurant-website-design": "Conception de sites pour restaurants et cafés", "small-business-web-design": "Conception web pour petites entreprises", "mobile-app-design": "Conception d’applications mobiles", "custom-software-development": "Développement de logiciels sur mesure", "brand-identity-design": "Conception de marque et d’identité visuelle" } },
    home: { eyebrow: "Web · Mobile · Logiciel", title: "Nous concevons votre site web,", titleAccent: "à votre façon.", intro: "Conception et développement web à Montréal pour les entreprises du Québec, du Canada et du monde entier. Nous créons des boutiques en ligne, des sites pour restaurants et cafés, des pages de destination, des applications mobiles et des logiciels sur mesure.", primaryCta: "Démarrer votre projet", secondaryCta: "À propos d’Arash", imageAlt: "Site web adaptatif affiché sur un téléphone et un ordinateur portable", processEyebrow: "Notre méthode", processTitle: "De l’idée au lancement", steps: [{ title: "Découverte", description: "Nous écoutons votre vision, vos besoins et vos objectifs." }, { title: "Conception", description: "Des concepts épurés adaptés à votre marque et à votre public." }, { title: "Réalisation", description: "Un développement soigné pour le web, le mobile et les logiciels." }, { title: "Lancement", description: "Nous livrons, optimisons et soutenons votre produit partout dans le monde." }], ctaTitle: "Prêt à créer quelque chose de remarquable?", ctaText: "Parlez-nous de votre entreprise et nous concevrons un site, une application ou une plateforme qui la met en valeur.", ctaButton: "Parlons-en" },
    about: { eyebrow: "À propos", title: "Studio indépendant.", titleAccent: "Service personnalisé.", intro: "Arash Ammarlooi a fondé et dirige ce studio web indépendant de Montréal. Depuis 2013, le studio conçoit et réalise des expériences numériques pour des clients au Canada et partout dans le monde.", statLabels: ["Années d’expérience", "Projets réalisés", "Pays desservis", "Passion pour le design"], storyTitle: "Dirigé par Arash, centré sur", storyTitleAccent: "vos objectifs", storyParagraphs: ["Arash Ammarlooi est le fondateur et concepteur principal d’Arash Web Studio à Montréal, au Québec. Chaque client travaille directement avec lui, du premier échange au lancement. Lorsqu’un projet exige une expertise supplémentaire, il collabore avec des designers et développeurs indépendants de confiance.", "Travailler au-delà des frontières et des cultures nous a appris une chose essentielle : un excellent design est universel, mais un excellent service est personnel. Où que vous soyez et quelle que soit votre activité, nous concevons autour de vous — vos clients, votre marché et votre vision."], imageAlt: "Globe représentant les clients servis à Montréal, au Canada et dans le monde", valuesEyebrow: "Ce qui nous anime", valuesTitle: "Nos valeurs", values: [{ title: "Collaboration flexible", description: "Arash dirige chaque projet et fait appel à des designers ou développeurs indépendants de confiance lorsqu’une expertise supplémentaire est nécessaire." }, { title: "Le souci du détail", description: "Treize années à perfectionner notre métier rendent chaque pixel, chaque animation et chaque interaction intentionnels." }, { title: "Une vision axée sur l’entreprise", description: "La beauté ne suffit pas. Chaque projet vise la croissance de votre entreprise — plus de clients, plus de ventes et plus d’impact." }, { title: "Un véritable partenariat", description: "De la première esquisse jusqu’après le lancement, nous travaillons à vos côtés. Vos objectifs deviennent les nôtres." }], ctaTitle: "Vous souhaitez un service personnalisé appuyé par", ctaAccent: "une expérience concrète?", ctaButton: "Nous joindre" },
    contact: { eyebrow: "Contact", title: "Créons quelque chose de", titleAccent: "remarquable.", intro: "Parlez de votre projet à Arash Ammarlooi — site web, boutique en ligne, application ou toute autre idée. Vous recevrez généralement une réponse dans les 24 heures.", directTitle: "Contact direct", directText: "Travaillez directement avec Arash dès le premier échange. Appelez, textez ou écrivez-lui pour discuter de votre projet.", phone: "Téléphone", email: "Courriel", serviceArea: "Zone desservie", serviceAreaValue: "Montréal, Québec · Canada et monde entier", experience: "Plus de 13 ans d’expérience · projets réalisés dans 14 pays.", formTitle: "Démarrer votre projet", name: "Votre nom", emailPlaceholder: "Votre courriel", phonePlaceholder: "Téléphone (facultatif)", projectType: "Type de projet", projectOptions: options(["Site web d’entreprise", "Boutique en ligne", "Restaurant / Café", "Publicité / Page de destination", "Application mobile", "Logiciel sur mesure", "Autre"]), details: "Parlez-nous de votre projet", sending: "Envoi en cours...", send: "Envoyer le message", success: "Message envoyé! Nous vous répondrons dans les 24 heures.", genericError: "Une erreur est survenue.", errorFallback: "Vous pouvez aussi nous écrire directement à" },
    metadata: { homeTitle: "Conception web à Montréal | Arash Web Studio", homeDescription: "Designer web à Montréal créant des sites, boutiques en ligne, applications mobiles et logiciels sur mesure pour des entreprises du Québec, du Canada et du monde entier.", aboutTitle: "À propos d’Arash Ammarlooi", aboutDescription: "Découvrez Arash Ammarlooi, fondateur et designer principal d’Arash Web Studio à Montréal, ainsi que son approche collaborative des projets numériques.", contactTitle: "Contacter un designer web à Montréal", contactDescription: "Contactez Arash Ammarlooi, designer web à Montréal, pour discuter d’un site d’entreprise, d’une boutique en ligne, d’une application mobile ou d’un logiciel sur mesure." },
  },
  es: {
    nav: { home: "Inicio", about: "Nosotros", services: "Servicios", blog: "Blog", contact: "Contacto", startProject: "Iniciar un proyecto", primaryLabel: "Navegación principal", mobileLabel: "Navegación móvil", openMenu: "Abrir menú", closeMenu: "Cerrar menú", homeLabel: "Inicio de Arash Web Studio", languageLabel: "Idioma" },
    footer: { description: "Fundado y dirigido por Arash Ammarlooi en Montreal. Diseño web independiente, comercio electrónico, aplicaciones y software a medida para empresas de Canadá y de todo el mundo.", pages: "Páginas", services: "Servicios", getInTouch: "Contacto", location: "Montreal, Quebec", serviceArea: "Atendemos a Canadá y a clientes de todo el mundo", copyright: "Fundado y dirigido por Arash Ammarlooi.", serviceTitles: { "ecommerce-web-design": "Diseño de sitios de comercio electrónico", "restaurant-website-design": "Diseño web para restaurantes y cafeterías", "small-business-web-design": "Diseño web para pequeñas empresas", "mobile-app-design": "Diseño de aplicaciones móviles", "custom-software-development": "Desarrollo de software a medida", "brand-identity-design": "Diseño de marca e identidad visual" } },
    home: { eyebrow: "Web · Móvil · Software", title: "Diseñamos tu sitio web,", titleAccent: "a tu manera.", intro: "Diseño y desarrollo web en Montreal para empresas de Quebec, Canadá y todo el mundo. Creamos tiendas en línea, sitios para restaurantes y cafeterías, páginas de destino, aplicaciones móviles y software a medida.", primaryCta: "Inicia tu proyecto", secondaryCta: "Sobre Arash", imageAlt: "Diseño web adaptable mostrado en un teléfono y un portátil", processEyebrow: "Cómo funciona", processTitle: "De la idea al lanzamiento", steps: [{ title: "Descubrimiento", description: "Escuchamos tu visión, tu negocio y tus objetivos." }, { title: "Diseño", description: "Conceptos claros creados para tu marca y tu público." }, { title: "Desarrollo", description: "Desarrollo meticuloso para web, móvil y software." }, { title: "Lanzamiento", description: "Publicamos, optimizamos y damos soporte a tu producto en todo el mundo." }], ctaTitle: "¿Listo para crear algo extraordinario?", ctaText: "Cuéntanos sobre tu negocio y diseñaremos un sitio, una aplicación o una plataforma que lo haga destacar.", ctaButton: "Hablemos" },
    about: { eyebrow: "Nosotros", title: "Estudio independiente.", titleAccent: "Servicio personal.", intro: "Arash Ammarlooi fundó y dirige este estudio web independiente de Montreal. Desde 2013, el estudio diseña y desarrolla experiencias digitales para clientes de Canadá y de todo el mundo.", statLabels: ["Años de experiencia", "Proyectos entregados", "Países alcanzados", "Pasión por el diseño"], storyTitle: "Dirigido por Arash, centrado en", storyTitleAccent: "tus objetivos", storyParagraphs: ["Arash Ammarlooi es el fundador y diseñador principal de Arash Web Studio en Montreal, Quebec. Cada cliente trabaja directamente con él desde la primera conversación hasta el lanzamiento. Cuando un proyecto requiere experiencia adicional, colabora con diseñadores y desarrolladores independientes de confianza.", "Trabajar entre países y culturas nos enseñó algo valioso: el gran diseño es universal, pero el gran servicio es personal. No importa dónde estés ni cuál sea tu negocio, diseñamos pensando en ti: tus clientes, tu mercado y tu visión."], imageAlt: "Globo que representa a clientes atendidos en Montreal, Canadá y todo el mundo", valuesEyebrow: "Lo que nos impulsa", valuesTitle: "Nuestros valores", values: [{ title: "Colaboración flexible", description: "Arash dirige cada proyecto e incorpora a diseñadores o desarrolladores independientes de confianza cuando se necesita experiencia adicional." }, { title: "La calidad ante todo", description: "Trece años perfeccionando nuestro oficio hacen que cada píxel, animación e interacción sea intencional." }, { title: "Pensamiento empresarial", description: "La belleza no basta. Cada proyecto busca hacer crecer tu negocio: más clientes, más ventas y más impacto." }, { title: "Una verdadera alianza", description: "Desde el primer boceto hasta mucho después del lanzamiento, trabajamos a tu lado. Tus objetivos se convierten en los nuestros." }], ctaTitle: "¿Quieres un servicio personal respaldado por", ctaAccent: "experiencia real?", ctaButton: "Contáctanos" },
    contact: { eyebrow: "Contacto", title: "Hagamos algo", titleAccent: "extraordinario.", intro: "Cuéntale a Arash Ammarlooi sobre tu proyecto: un sitio web, una tienda en línea, una aplicación o cualquier otra idea. Normalmente recibirás una respuesta en 24 horas.", directTitle: "Contacto directo", directText: "Trabaja directamente con Arash desde la primera conversación. Llama, envía un mensaje de texto o un correo para hablar sobre tu proyecto.", phone: "Teléfono", email: "Correo electrónico", serviceArea: "Área de servicio", serviceAreaValue: "Montreal, Quebec · Canadá y todo el mundo", experience: "Más de 13 años de experiencia · proyectos entregados en 14 países.", formTitle: "Inicia tu proyecto", name: "Tu nombre", emailPlaceholder: "Tu correo electrónico", phonePlaceholder: "Teléfono (opcional)", projectType: "Tipo de proyecto", projectOptions: options(["Sitio web empresarial", "Tienda en línea", "Restaurante / Cafetería", "Publicidad / Página de destino", "Aplicación móvil", "Software a medida", "Otro"]), details: "Cuéntanos sobre tu proyecto", sending: "Enviando...", send: "Enviar mensaje", success: "¡Mensaje enviado! Te responderemos en un plazo de 24 horas.", genericError: "Algo salió mal.", errorFallback: "También puedes escribirnos directamente a" },
    metadata: { homeTitle: "Diseño web en Montreal | Arash Web Studio", homeDescription: "Diseñador web en Montreal que crea sitios, tiendas en línea, aplicaciones móviles y software a medida para empresas de Quebec, Canadá y todo el mundo.", aboutTitle: "Sobre Arash Ammarlooi", aboutDescription: "Conoce a Arash Ammarlooi, fundador y diseñador principal de Arash Web Studio en Montreal, y su enfoque colaborativo para proyectos digitales.", contactTitle: "Contacta a un diseñador web en Montreal", contactDescription: "Contacta a Arash Ammarlooi, diseñador web en Montreal, para hablar de un sitio empresarial, una tienda en línea, una aplicación móvil o software a medida." },
  },
  de: {
    nav: { home: "Startseite", about: "Über uns", services: "Leistungen", blog: "Blog", contact: "Kontakt", startProject: "Projekt starten", primaryLabel: "Hauptnavigation", mobileLabel: "Mobile Navigation", openMenu: "Menü öffnen", closeMenu: "Menü schließen", homeLabel: "Arash Web Studio Startseite", languageLabel: "Sprache" },
    footer: { description: "Gegründet und geleitet von Arash Ammarlooi in Montreal. Unabhängiges Webdesign, E-Commerce, Apps und individuelle Software für Unternehmen in Kanada und weltweit.", pages: "Seiten", services: "Leistungen", getInTouch: "Kontakt", location: "Montreal, Quebec", serviceArea: "Für Kanada und Kunden weltweit", copyright: "Gegründet und geleitet von Arash Ammarlooi.", serviceTitles: { "ecommerce-web-design": "E-Commerce-Webdesign", "restaurant-website-design": "Webdesign für Restaurants und Cafés", "small-business-web-design": "Webdesign für kleine Unternehmen", "mobile-app-design": "Design mobiler Apps", "custom-software-development": "Individuelle Softwareentwicklung", "brand-identity-design": "Marken- und visuelles Identitätsdesign" } },
    home: { eyebrow: "Web · Mobil · Software", title: "Wir gestalten Ihre Website", titleAccent: "nach Ihren Vorstellungen.", intro: "Webdesign und -entwicklung aus Montreal für Unternehmen in Quebec, Kanada und weltweit. Wir erstellen Onlineshops, Websites für Restaurants und Cafés, Landingpages, mobile Apps und individuelle Software.", primaryCta: "Projekt starten", secondaryCta: "Über Arash", imageAlt: "Responsives Webdesign auf einem Smartphone und Laptop", processEyebrow: "So funktioniert es", processTitle: "Von der Idee bis zum Start", steps: [{ title: "Entdecken", description: "Wir hören Ihrer Vision, Ihrem Unternehmen und Ihren Zielen zu." }, { title: "Gestalten", description: "Klare Konzepte, abgestimmt auf Ihre Marke und Zielgruppe." }, { title: "Entwickeln", description: "Sorgfältige Entwicklung für Web, Mobilgeräte und Software." }, { title: "Veröffentlichen", description: "Wir veröffentlichen, optimieren und betreuen Ihr Produkt weltweit." }], ctaTitle: "Bereit, etwas Großartiges zu schaffen?", ctaText: "Erzählen Sie uns von Ihrem Unternehmen. Wir gestalten eine Website, App oder Plattform, die es ins beste Licht rückt.", ctaButton: "Lassen Sie uns sprechen" },
    about: { eyebrow: "Über uns", title: "Unabhängiges Studio.", titleAccent: "Persönlicher Service.", intro: "Arash Ammarlooi gründete und leitet dieses unabhängige Webstudio in Montreal. Seit 2013 gestaltet und entwickelt das Studio digitale Erlebnisse für Kunden in Kanada und weltweit.", statLabels: ["Jahre Erfahrung", "Abgeschlossene Projekte", "Erreichte Länder", "Leidenschaft für Design"], storyTitle: "Von Arash geleitet, auf", storyTitleAccent: "Ihre Ziele ausgerichtet", storyParagraphs: ["Arash Ammarlooi ist Gründer und leitender Designer des Arash Web Studio in Montreal, Quebec. Jeder Kunde arbeitet vom ersten Gespräch bis zum Start direkt mit ihm zusammen. Wenn ein Projekt zusätzliche Fachkenntnisse erfordert, arbeitet er mit bewährten unabhängigen Designern und Entwicklern zusammen.", "Die Arbeit über Länder- und Kulturgrenzen hinweg hat uns etwas Wertvolles gelehrt: Großartiges Design ist universell, aber großartiger Service ist persönlich. Ganz gleich, wo Sie sind oder was Ihr Unternehmen tut — wir gestalten für Sie, Ihre Kunden, Ihren Markt und Ihre Vision."], imageAlt: "Globus als Symbol für Kunden in Montreal, Kanada und weltweit", valuesEyebrow: "Was uns antreibt", valuesTitle: "Unsere Werte", values: [{ title: "Flexible Zusammenarbeit", description: "Arash leitet jedes Projekt und bezieht bewährte unabhängige Designer oder Entwickler ein, wenn zusätzliche Expertise gefragt ist." }, { title: "Handwerk an erster Stelle", description: "Dreizehn Jahre verfeinertes Handwerk bedeuten, dass jedes Pixel, jede Animation und jede Interaktion bewusst gestaltet ist." }, { title: "Unternehmerisches Denken", description: "Schönheit allein reicht nicht. Jedes Projekt soll Ihr Unternehmen voranbringen — mit mehr Kunden, mehr Umsatz und mehr Wirkung." }, { title: "Echte Partnerschaft", description: "Von der ersten Skizze bis lange nach dem Start arbeiten wir Seite an Seite mit Ihnen. Ihre Ziele werden zu unseren Zielen." }], ctaTitle: "Sie wünschen persönlichen Service mit", ctaAccent: "echter Erfahrung?", ctaButton: "Kontakt aufnehmen" },
    contact: { eyebrow: "Kontakt", title: "Lassen Sie uns etwas", titleAccent: "Großartiges schaffen.", intro: "Erzählen Sie Arash Ammarlooi von Ihrem Projekt — einer Website, einem Onlineshop, einer App oder etwas ganz anderem. In der Regel erhalten Sie innerhalb von 24 Stunden eine Antwort.", directTitle: "Direkter Kontakt", directText: "Arbeiten Sie vom ersten Gespräch an direkt mit Arash. Rufen Sie an oder schreiben Sie eine SMS oder E-Mail, um Ihr Projekt zu besprechen.", phone: "Telefon", email: "E-Mail", serviceArea: "Einsatzgebiet", serviceAreaValue: "Montreal, Quebec · Kanada und weltweit", experience: "Über 13 Jahre Erfahrung · Projekte in 14 Ländern umgesetzt.", formTitle: "Projekt starten", name: "Ihr Name", emailPlaceholder: "Ihre E-Mail-Adresse", phonePlaceholder: "Telefon (optional)", projectType: "Projektart", projectOptions: options(["Unternehmenswebsite", "Onlineshop", "Restaurant / Café", "Werbung / Landingpage", "Mobile App", "Individuelle Software", "Etwas anderes"]), details: "Erzählen Sie uns von Ihrem Projekt", sending: "Wird gesendet...", send: "Nachricht senden", success: "Nachricht gesendet! Wir melden uns innerhalb von 24 Stunden.", genericError: "Etwas ist schiefgelaufen.", errorFallback: "Sie können uns auch direkt eine E-Mail senden an" },
    metadata: { homeTitle: "Webdesign Montreal | Arash Web Studio", homeDescription: "Webdesigner in Montreal für Websites, Onlineshops, mobile Apps und individuelle Software für Unternehmen in Quebec, Kanada und weltweit.", aboutTitle: "Über Arash Ammarlooi", aboutDescription: "Lernen Sie Arash Ammarlooi kennen, Gründer und leitender Designer des Arash Web Studio in Montreal, und erfahren Sie mehr über seinen kooperativen Ansatz.", contactTitle: "Webdesigner in Montreal kontaktieren", contactDescription: "Kontaktieren Sie Arash Ammarlooi, Webdesigner in Montreal, für eine Unternehmenswebsite, einen Onlineshop, eine mobile App oder individuelle Software." },
  },
  it: {
    nav: { home: "Home", about: "Chi siamo", services: "Servizi", blog: "Blog", contact: "Contatti", startProject: "Avvia un progetto", primaryLabel: "Navigazione principale", mobileLabel: "Navigazione mobile", openMenu: "Apri menu", closeMenu: "Chiudi menu", homeLabel: "Home di Arash Web Studio", languageLabel: "Lingua" },
    footer: { description: "Fondato e diretto da Arash Ammarlooi a Montreal. Web design indipendente, e-commerce, app e software su misura per aziende in Canada e nel mondo.", pages: "Pagine", services: "Servizi", getInTouch: "Contatti", location: "Montreal, Quebec", serviceArea: "Al servizio del Canada e di clienti in tutto il mondo", copyright: "Fondato e diretto da Arash Ammarlooi.", serviceTitles: { "ecommerce-web-design": "Progettazione di siti e-commerce", "restaurant-website-design": "Siti web per ristoranti e caffè", "small-business-web-design": "Web design per piccole imprese", "mobile-app-design": "Progettazione di applicazioni mobili", "custom-software-development": "Sviluppo software su misura", "brand-identity-design": "Brand e identità visiva" } },
    home: { eyebrow: "Web · Mobile · Software", title: "Progettiamo il tuo sito web,", titleAccent: "a modo tuo.", intro: "Web design e sviluppo a Montreal per aziende in Quebec, in Canada e nel mondo. Creiamo negozi online, siti per ristoranti e caffè, landing page, app mobili e software su misura.", primaryCta: "Avvia il tuo progetto", secondaryCta: "Chi è Arash", imageAlt: "Design web responsivo visualizzato su smartphone e laptop", processEyebrow: "Come funziona", processTitle: "Dall’idea al lancio", steps: [{ title: "Scoperta", description: "Ascoltiamo la tua visione, la tua attività e i tuoi obiettivi." }, { title: "Progettazione", description: "Concept essenziali creati per il tuo brand e il tuo pubblico." }, { title: "Sviluppo", description: "Sviluppo accurato per web, dispositivi mobili e software." }, { title: "Lancio", description: "Pubblichiamo, ottimizziamo e supportiamo il tuo prodotto in tutto il mondo." }], ctaTitle: "Pronto a creare qualcosa di straordinario?", ctaText: "Raccontaci la tua attività e progetteremo un sito, un’app o una piattaforma che la faccia risaltare.", ctaButton: "Parliamone" },
    about: { eyebrow: "Chi siamo", title: "Studio indipendente.", titleAccent: "Servizio personale.", intro: "Arash Ammarlooi ha fondato e dirige questo studio web indipendente di Montreal. Dal 2013, lo studio progetta e realizza esperienze digitali per clienti in Canada e nel mondo.", statLabels: ["Anni di esperienza", "Progetti consegnati", "Paesi raggiunti", "Passione per il design"], storyTitle: "Guidato da Arash, costruito intorno ai", storyTitleAccent: "tuoi obiettivi", storyParagraphs: ["Arash Ammarlooi è il fondatore e lead designer di Arash Web Studio a Montreal, Quebec. Ogni cliente lavora direttamente con lui, dal primo colloquio al lancio. Quando un progetto richiede competenze aggiuntive, collabora con designer e sviluppatori indipendenti di fiducia.", "Lavorare tra paesi e culture ci ha insegnato una cosa importante: il grande design è universale, ma il grande servizio è personale. Ovunque tu sia e qualunque sia la tua attività, progettiamo intorno a te — ai tuoi clienti, al tuo mercato e alla tua visione."], imageAlt: "Globo che rappresenta i clienti serviti a Montreal, in Canada e nel mondo", valuesEyebrow: "Ciò che ci guida", valuesTitle: "I nostri valori", values: [{ title: "Collaborazione flessibile", description: "Arash guida ogni progetto e coinvolge designer o sviluppatori indipendenti di fiducia quando servono competenze aggiuntive." }, { title: "La qualità prima di tutto", description: "Tredici anni dedicati a perfezionare il nostro mestiere rendono intenzionale ogni pixel, animazione e interazione." }, { title: "Mentalità orientata al business", description: "La bellezza non basta. Ogni progetto è pensato per far crescere la tua attività — più clienti, più vendite, più impatto." }, { title: "Una vera partnership", description: "Dal primo schizzo fino a molto tempo dopo il lancio, lavoriamo al tuo fianco. I tuoi obiettivi diventano i nostri." }], ctaTitle: "Vuoi un servizio personale sostenuto da", ctaAccent: "esperienza concreta?", ctaButton: "Contattaci" },
    contact: { eyebrow: "Contatti", title: "Creiamo qualcosa di", titleAccent: "straordinario.", intro: "Racconta ad Arash Ammarlooi il tuo progetto — un sito web, un negozio online, un’app o qualsiasi altra idea. Di solito riceverai una risposta entro 24 ore.", directTitle: "Contatto diretto", directText: "Lavora direttamente con Arash fin dal primo colloquio. Chiama, invia un messaggio o un’e-mail per parlare del tuo progetto.", phone: "Telefono", email: "E-mail", serviceArea: "Area servita", serviceAreaValue: "Montreal, Quebec · Canada e tutto il mondo", experience: "Oltre 13 anni di esperienza · progetti consegnati in 14 paesi.", formTitle: "Avvia il tuo progetto", name: "Il tuo nome", emailPlaceholder: "La tua e-mail", phonePlaceholder: "Telefono (facoltativo)", projectType: "Tipo di progetto", projectOptions: options(["Sito web aziendale", "Negozio e-commerce", "Ristorante / Caffè", "Pubblicità / Landing page", "Applicazione mobile", "Software su misura", "Altro"]), details: "Raccontaci il tuo progetto", sending: "Invio in corso...", send: "Invia messaggio", success: "Messaggio inviato! Ti risponderemo entro 24 ore.", genericError: "Qualcosa è andato storto.", errorFallback: "Puoi anche scriverci direttamente a" },
    metadata: { homeTitle: "Web design a Montreal | Arash Web Studio", homeDescription: "Web designer a Montreal per siti, negozi e-commerce, app mobili e software su misura destinati ad aziende in Quebec, Canada e nel mondo.", aboutTitle: "Chi è Arash Ammarlooi", aboutDescription: "Conosci Arash Ammarlooi, fondatore e lead designer di Arash Web Studio a Montreal, e il suo approccio collaborativo ai progetti digitali.", contactTitle: "Contatta un web designer a Montreal", contactDescription: "Contatta Arash Ammarlooi, web designer a Montreal, per parlare di un sito aziendale, un negozio online, un’app mobile o software su misura." },
  },
  pt: {
    nav: { home: "Início", about: "Sobre", services: "Serviços", blog: "Blog", contact: "Contato", startProject: "Iniciar um projeto", primaryLabel: "Navegação principal", mobileLabel: "Navegação móvel", openMenu: "Abrir menu", closeMenu: "Fechar menu", homeLabel: "Início da Arash Web Studio", languageLabel: "Idioma" },
    footer: { description: "Fundado e liderado por Arash Ammarlooi em Montreal. Design de sites independente, comércio eletrônico, aplicativos e software sob medida para empresas no Canadá e no mundo.", pages: "Páginas", services: "Serviços", getInTouch: "Entre em contato", location: "Montreal, Quebec", serviceArea: "Atendemos o Canadá e clientes em todo o mundo", copyright: "Fundado e liderado por Arash Ammarlooi.", serviceTitles: { "ecommerce-web-design": "Design de sites de comércio eletrônico", "restaurant-website-design": "Sites para restaurantes e cafés", "small-business-web-design": "Web design para pequenas empresas", "mobile-app-design": "Design de aplicativos móveis", "custom-software-development": "Desenvolvimento de software sob medida", "brand-identity-design": "Design de marca e identidade visual" } },
    home: { eyebrow: "Web · Mobile · Software", title: "Criamos o seu site,", titleAccent: "do seu jeito.", intro: "Design e desenvolvimento de sites em Montreal para empresas no Quebec, em todo o Canadá e no mundo. Criamos lojas virtuais, sites para restaurantes e cafés, landing pages, aplicativos móveis e software sob medida.", primaryCta: "Inicie seu projeto", secondaryCta: "Sobre Arash", imageAlt: "Design responsivo exibido em um celular e um notebook", processEyebrow: "Como funciona", processTitle: "Da ideia ao lançamento", steps: [{ title: "Descoberta", description: "Ouvimos sua visão, seu negócio e seus objetivos." }, { title: "Design", description: "Conceitos claros criados para sua marca e seu público." }, { title: "Desenvolvimento", description: "Desenvolvimento cuidadoso para web, mobile e software." }, { title: "Lançamento", description: "Publicamos, otimizamos e apoiamos seu produto em todo o mundo." }], ctaTitle: "Pronto para criar algo incrível?", ctaText: "Conte-nos sobre seu negócio e criaremos um site, aplicativo ou plataforma que o faça brilhar.", ctaButton: "Vamos conversar" },
    about: { eyebrow: "Sobre", title: "Estúdio independente.", titleAccent: "Atendimento pessoal.", intro: "Arash Ammarlooi fundou e lidera este estúdio web independente em Montreal. Desde 2013, o estúdio projeta e desenvolve experiências digitais para clientes no Canadá e em todo o mundo.", statLabels: ["Anos de experiência", "Projetos entregues", "Países alcançados", "Paixão por design"], storyTitle: "Liderado por Arash, construído em torno dos", storyTitleAccent: "seus objetivos", storyParagraphs: ["Arash Ammarlooi é o fundador e designer principal da Arash Web Studio em Montreal, Quebec. Cada cliente trabalha diretamente com ele desde a primeira conversa até o lançamento. Quando um projeto exige conhecimento adicional, ele colabora com designers e desenvolvedores independentes de confiança.", "Trabalhar entre países e culturas nos ensinou algo valioso: um ótimo design é universal, mas um ótimo atendimento é pessoal. Não importa onde você esteja ou qual seja seu negócio, projetamos em torno de você — seus clientes, seu mercado e sua visão."], imageAlt: "Globo representando clientes atendidos em Montreal, no Canadá e no mundo", valuesEyebrow: "O que nos move", valuesTitle: "Nossos valores", values: [{ title: "Colaboração flexível", description: "Arash lidera cada projeto e envolve designers ou desenvolvedores independentes de confiança quando é necessário conhecimento adicional." }, { title: "Qualidade acima de tudo", description: "Treze anos aperfeiçoando nosso trabalho tornam intencionais cada pixel, animação e interação." }, { title: "Pensamento voltado ao negócio", description: "Beleza não basta. Cada projeto é criado para fazer seu negócio crescer — mais clientes, mais vendas e mais impacto." }, { title: "Parceria verdadeira", description: "Do primeiro esboço até muito depois do lançamento, trabalhamos ao seu lado. Seus objetivos se tornam os nossos." }], ctaTitle: "Quer um atendimento pessoal respaldado por", ctaAccent: "experiência real?", ctaButton: "Entre em contato" },
    contact: { eyebrow: "Contato", title: "Vamos criar algo", titleAccent: "incrível.", intro: "Conte a Arash Ammarlooi sobre seu projeto — um site, uma loja virtual, um aplicativo ou qualquer outra ideia. Normalmente, você receberá uma resposta em até 24 horas.", directTitle: "Contato direto", directText: "Trabalhe diretamente com Arash desde a primeira conversa. Ligue, envie uma mensagem ou um e-mail para falar sobre seu projeto.", phone: "Telefone", email: "E-mail", serviceArea: "Área de atendimento", serviceAreaValue: "Montreal, Quebec · Canadá e todo o mundo", experience: "Mais de 13 anos de experiência · projetos entregues em 14 países.", formTitle: "Inicie seu projeto", name: "Seu nome", emailPlaceholder: "Seu e-mail", phonePlaceholder: "Telefone (opcional)", projectType: "Tipo de projeto", projectOptions: options(["Site empresarial", "Loja virtual", "Restaurante / Café", "Publicidade / Landing page", "Aplicativo móvel", "Software sob medida", "Outro"]), details: "Conte-nos sobre seu projeto", sending: "Enviando...", send: "Enviar mensagem", success: "Mensagem enviada! Responderemos em até 24 horas.", genericError: "Algo deu errado.", errorFallback: "Você também pode nos enviar um e-mail diretamente para" },
    metadata: { homeTitle: "Web design em Montreal | Arash Web Studio", homeDescription: "Web designer em Montreal criando sites, lojas virtuais, aplicativos móveis e software sob medida para empresas no Quebec, Canadá e no mundo.", aboutTitle: "Sobre Arash Ammarlooi", aboutDescription: "Conheça Arash Ammarlooi, fundador e designer principal da Arash Web Studio em Montreal, e sua abordagem colaborativa para projetos digitais.", contactTitle: "Contate um web designer em Montreal", contactDescription: "Entre em contato com Arash Ammarlooi, web designer em Montreal, para conversar sobre um site empresarial, loja virtual, aplicativo móvel ou software sob medida." },
  },
  zh: {
    nav: { home: "首页", about: "关于我们", services: "服务", blog: "博客", contact: "联系", startProject: "启动项目", primaryLabel: "主导航", mobileLabel: "移动端导航", openMenu: "打开菜单", closeMenu: "关闭菜单", homeLabel: "Arash Web Studio 首页", languageLabel: "语言" },
    footer: { description: "由 Arash Ammarlooi 在蒙特利尔创立并亲自领导。为加拿大及全球企业提供独立网站设计、电子商务、应用程序和定制软件服务。", pages: "页面", services: "服务", getInTouch: "联系我们", location: "加拿大魁北克省蒙特利尔", serviceArea: "服务加拿大及全球客户", copyright: "由 Arash Ammarlooi 创立并领导。", serviceTitles: { "ecommerce-web-design": "电子商务网站设计", "restaurant-website-design": "餐厅与咖啡馆网站设计", "small-business-web-design": "小型企业网站设计", "mobile-app-design": "移动应用设计", "custom-software-development": "定制软件开发", "brand-identity-design": "品牌与视觉识别设计" } },
    home: { eyebrow: "网站 · 移动应用 · 软件", title: "我们按您的想法", titleAccent: "设计网站。", intro: "面向魁北克、加拿大及全球企业的蒙特利尔网站设计与开发服务。我们打造电子商务商店、餐厅和咖啡馆网站、着陆页、移动应用及定制软件。", primaryCta: "启动您的项目", secondaryCta: "了解 Arash", imageAlt: "在手机和笔记本电脑上展示的响应式网站设计", processEyebrow: "合作流程", processTitle: "从构想到上线", steps: [{ title: "了解", description: "我们倾听您的愿景、业务需求和目标。" }, { title: "设计", description: "围绕您的品牌与受众打造简洁的设计方案。" }, { title: "开发", description: "精心完成网站、移动应用与软件开发。" }, { title: "上线", description: "我们在全球范围内发布、优化并持续支持您的产品。" }], ctaTitle: "准备好打造出色的产品了吗？", ctaText: "告诉我们您的业务，我们将设计一个让它脱颖而出的网站、应用或平台。", ctaButton: "联系我们" },
    about: { eyebrow: "关于我们", title: "独立工作室，", titleAccent: "个性化服务。", intro: "Arash Ammarlooi 创立并领导这家位于蒙特利尔的独立网站工作室。自 2013 年以来，工作室为加拿大及全球客户设计和打造数字体验。", statLabels: ["年行业经验", "已交付项目", "服务覆盖国家", "对设计的热忱"], storyTitle: "由 Arash 亲自领导，围绕", storyTitleAccent: "您的目标打造", storyParagraphs: ["Arash Ammarlooi 是位于魁北克省蒙特利尔的 Arash Web Studio 创始人兼首席设计师。从首次沟通到项目上线，每位客户都直接与他合作。当项目需要额外专业能力时，他会与值得信赖的独立设计师和开发人员协作。", "跨越不同国家和文化的工作经历让我们明白：优秀的设计具有普适性，而优秀的服务必须因人而异。无论您身在何处、从事何种业务，我们都围绕您来设计——您的客户、市场与愿景。"], imageAlt: "代表蒙特利尔、加拿大及全球客户的地球图像", valuesEyebrow: "我们的动力", valuesTitle: "我们的价值观", values: [{ title: "灵活协作", description: "Arash 亲自领导每个项目，并在需要额外专业能力时邀请值得信赖的独立设计师或开发人员参与。" }, { title: "品质至上", description: "十三年的不断打磨，让每个像素、每段动画和每次交互都有明确目的。" }, { title: "以业务为先", description: "美观还不够。每个项目都旨在推动您的业务增长——赢得更多客户、销售与影响力。" }, { title: "真正的伙伴关系", description: "从第一张草图到上线后的长期支持，我们始终与您并肩合作。您的目标就是我们的目标。" }], ctaTitle: "希望获得由真实经验支撑的", ctaAccent: "个性化服务吗？", ctaButton: "联系我们" },
    contact: { eyebrow: "联系我们", title: "让我们一起打造", titleAccent: "出色的产品。", intro: "向 Arash Ammarlooi 介绍您的项目——无论是网站、网上商店、应用还是其他想法。您通常会在 24 小时内收到回复。", directTitle: "直接联系", directText: "从第一次沟通开始就直接与 Arash 合作。您可以致电、发短信或发送电子邮件讨论项目。", phone: "电话", email: "电子邮件", serviceArea: "服务范围", serviceAreaValue: "蒙特利尔、魁北克 · 加拿大及全球", experience: "13 年以上经验 · 已在 14 个国家交付项目。", formTitle: "启动您的项目", name: "您的姓名", emailPlaceholder: "您的电子邮箱", phonePlaceholder: "电话（选填）", projectType: "项目类型", projectOptions: options(["企业网站", "电子商务商店", "餐厅 / 咖啡馆", "广告 / 着陆页", "移动应用", "定制软件", "其他"]), details: "请介绍您的项目", sending: "正在发送……", send: "发送消息", success: "消息已发送！我们将在 24 小时内回复您。", genericError: "出现错误。", errorFallback: "您也可以直接发送电子邮件至" },
    metadata: { homeTitle: "蒙特利尔网站设计 | Arash Web Studio", homeDescription: "蒙特利尔网站设计师，为魁北克、加拿大及全球企业打造网站、电子商务商店、移动应用和定制软件。", aboutTitle: "关于 Arash Ammarlooi", aboutDescription: "了解蒙特利尔 Arash Web Studio 的创始人兼首席设计师 Arash Ammarlooi，以及他的协作式数字项目方法。", contactTitle: "联系蒙特利尔网站设计师", contactDescription: "联系蒙特利尔网站设计师 Arash Ammarlooi，讨论企业网站、电子商务商店、移动应用或定制软件项目。" },
  },
};

export function getPageTranslations(locale: Locale) {
  return pageTranslations[locale];
}
