import type { Locale } from "@/lib/i18n";

type Step = { title: string; description: string };
type Value = { title: string; description: string };
type ProjectOption = { value: string; label: string };

export type PageTranslations = {
  nav: {
    home: string;
    about: string;
    services: string;
    blog: string;
    contact: string;
    startProject: string;
    primaryLabel: string;
    mobileLabel: string;
    openMenu: string;
    closeMenu: string;
    homeLabel: string;
    languageLabel: string;
  };
  footer: {
    description: string;
    pages: string;
    services: string;
    getInTouch: string;
    location: string;
    serviceArea: string;
    copyright: string;
    serviceTitles: Record<string, string>;
  };
  home: {
    eyebrow: string;
    title: string;
    titleAccent: string;
    intro: string;
    primaryCta: string;
    secondaryCta: string;
    imageAlt: string;
    processEyebrow: string;
    processTitle: string;
    steps: Step[];
    ctaTitle: string;
    ctaText: string;
    ctaButton: string;
  };
  about: {
    eyebrow: string;
    title: string;
    titleAccent: string;
    intro: string;
    statLabels: [string, string, string, string];
    storyTitle: string;
    storyTitleAccent: string;
    storyParagraphs: [string, string];
    imageAlt: string;
    valuesEyebrow: string;
    valuesTitle: string;
    values: Value[];
    ctaTitle: string;
    ctaAccent: string;
    ctaButton: string;
  };
  contact: {
    eyebrow: string;
    title: string;
    titleAccent: string;
    intro: string;
    directTitle: string;
    directText: string;
    phone: string;
    email: string;
    serviceArea: string;
    serviceAreaValue: string;
    experience: string;
    formTitle: string;
    name: string;
    emailPlaceholder: string;
    phonePlaceholder: string;
    projectType: string;
    projectOptions: ProjectOption[];
    details: string;
    sending: string;
    send: string;
    success: string;
    genericError: string;
    errorFallback: string;
  };
  metadata: {
    homeTitle: string;
    homeDescription: string;
    aboutTitle: string;
    aboutDescription: string;
    contactTitle: string;
    contactDescription: string;
  };
};

const serviceValues = [
  "Business Website",
  "E-commerce Store",
  "Booking / Appointment Website",
  "Advertising / Campaign Landing Page",
  "Mobile Application",
  "Custom Software",
  "Something Else",
] as const;

function options(labels: readonly string[]): ProjectOption[] {
  return serviceValues.map((value, index) => ({ value, label: labels[index] }));
}

export const pageTranslations: Record<Locale, PageTranslations> = {
  en: {
    nav: { home: "Home", about: "About", services: "Services", blog: "Blog", contact: "Contact", startProject: "Start a Project", primaryLabel: "Primary navigation", mobileLabel: "Mobile navigation", openMenu: "Open menu", closeMenu: "Close menu", homeLabel: "Arash Web Studio home", languageLabel: "Language" },
    footer: {
      description: "Arash Web Studio designs responsive websites, e-commerce experiences, booking systems, mobile apps and custom software for small and medium-sized businesses worldwide.",
      pages: "Pages", services: "Services", getInTouch: "Get in touch", location: "Remote digital studio", serviceArea: "Working with clients worldwide", copyright: "Web design and digital solutions worldwide.",
      serviceTitles: { "ecommerce-web-design": "E-commerce Website Design", "booking-website-design": "Booking & Appointment Websites", "small-business-web-design": "Small & Medium Business Web Design", "mobile-app-design": "Mobile Application Design", "custom-software-development": "Custom Software Development", "brand-identity-design": "Brand & Visual Identity Design" },
    },
    home: {
      eyebrow: "Web · SEO · Mobile · Software", title: "Digital experiences built for", titleAccent: "business growth.", intro: "Responsive web design and development for small and medium-sized businesses anywhere in the world. We create business websites, e-commerce stores, booking and appointment experiences, advertising landing pages, mobile apps and custom software.", primaryCta: "Start Your Project", secondaryCta: "About the Studio", imageAlt: "Responsive website design displayed on a phone and laptop", processEyebrow: "How it works", processTitle: "From strategy to measurable growth",
      steps: [{ title: "Discover", description: "We listen to your vision, your business and your goals." }, { title: "Design", description: "Clean concepts crafted around your brand and audience." }, { title: "Build", description: "Careful development for web, mobile and software." }, { title: "Launch", description: "We ship, optimize and support your product worldwide." }],
      ctaTitle: "Ready to improve your digital presence?", ctaText: "Tell us about your goals and we will shape a responsive, search-ready website, app or platform around your business.", ctaButton: "Let's Talk",
    },
    about: {
      eyebrow: "About us", title: "Independent studio.", titleAccent: "Business-focused design.", intro: "Arash Web Studio is a digital design and development studio managed by Arash Ammarlooi. Since 2013, the studio has built practical digital experiences for organizations around the world.", statLabels: ["Years of experience", "Projects delivered", "Countries reached", "Commitment to quality"], storyTitle: "A flexible studio built around", storyTitleAccent: "your goals", storyParagraphs: ["Arash Web Studio combines strategy, design and development in one focused process. Clients have a clear point of contact from the first conversation through launch, with trusted specialists involved when a project needs additional expertise.", "The work is shaped around each organization, its audience and its market. The aim is not simply to launch an attractive page, but to create a useful, accessible and responsive digital experience that can support long-term growth."], imageAlt: "Globe representing businesses served worldwide", valuesEyebrow: "What drives us", valuesTitle: "Our values",
      values: [{ title: "Flexible Collaboration", description: "A focused core studio works with trusted independent specialists when a project needs additional expertise." }, { title: "Purposeful Craft", description: "Every layout, interaction and technical decision should serve the audience and the business goal." }, { title: "Business-First Thinking", description: "Design is connected to clear outcomes such as stronger credibility, qualified inquiries, bookings and sales." }, { title: "Long-Term Partnership", description: "The process includes clear communication, a dependable launch and room for continued improvement." }],
      ctaTitle: "Want personal service backed by", ctaAccent: "real experience?", ctaButton: "Get in Touch",
    },
    contact: {
      eyebrow: "Contact", title: "Let's make something", titleAccent: "useful.", intro: "Tell Arash Web Studio about your goals, audience, required pages or features, timeline and available content. You will usually receive a reply within 24 hours.", directTitle: "Contact the studio", directText: "Call, text or email to discuss a new website, redesign, e-commerce experience, booking flow, mobile app or custom platform.", phone: "Phone", email: "Email", serviceArea: "Service area", serviceAreaValue: "Available to businesses worldwide", experience: "13+ years of experience · projects delivered across 14 countries.", formTitle: "Start your project", name: "Your name", emailPlaceholder: "Your email", phonePlaceholder: "Phone (optional)", projectType: "Project type", projectOptions: options(serviceValues), details: "Tell us about your business, goals, audience, timeline and required features", sending: "Sending...", send: "Send Message", success: "Message sent! We'll get back to you within 24 hours.", genericError: "Something went wrong.", errorFallback: "You can also email us directly at",
    },
    metadata: { homeTitle: "Web Design, SEO & Development | Arash Web Studio", homeDescription: "Responsive websites, e-commerce, booking systems, mobile apps and custom software for small and medium-sized businesses worldwide.", aboutTitle: "About Arash Web Studio", aboutDescription: "Learn how Arash Web Studio approaches responsive design, SEO, content, development and long-term digital growth.", contactTitle: "Contact Arash Web Studio", contactDescription: "Contact the studio to discuss a responsive business website, e-commerce store, booking experience, mobile app or custom software project." },
  },
  fr: {
    nav: { home: "Accueil", about: "À propos", services: "Services", blog: "Blogue", contact: "Contact", startProject: "Démarrer un projet", primaryLabel: "Navigation principale", mobileLabel: "Navigation mobile", openMenu: "Ouvrir le menu", closeMenu: "Fermer le menu", homeLabel: "Accueil d’Arash Web Studio", languageLabel: "Langue" },
    footer: { description: "Arash Web Studio conçoit des sites adaptatifs, des expériences de commerce électronique, des systèmes de réservation, des applications mobiles et des logiciels sur mesure pour les petites et moyennes entreprises du monde entier.", pages: "Pages", services: "Services", getInTouch: "Nous joindre", location: "Studio numérique à distance", serviceArea: "Collaboration avec des clients du monde entier", copyright: "Conception web et solutions numériques dans le monde entier.", serviceTitles: { "ecommerce-web-design": "Conception de sites de commerce électronique", "booking-website-design": "Sites de réservation et de prise de rendez-vous", "small-business-web-design": "Conception web pour petites et moyennes entreprises", "mobile-app-design": "Conception d’applications mobiles", "custom-software-development": "Développement de logiciels sur mesure", "brand-identity-design": "Conception de marque et d’identité visuelle" } },
    home: { eyebrow: "Web · SEO · Mobile · Logiciel", title: "Des expériences numériques conçues pour", titleAccent: "faire progresser votre entreprise.", intro: "Conception et développement web adaptatifs pour les petites et moyennes entreprises partout dans le monde. Nous créons des sites d’entreprise, des boutiques en ligne, des parcours de réservation et de rendez-vous, des pages de campagne, des applications mobiles et des logiciels sur mesure.", primaryCta: "Démarrer votre projet", secondaryCta: "À propos du studio", imageAlt: "Site web adaptatif affiché sur un téléphone et un ordinateur portable", processEyebrow: "Notre méthode", processTitle: "De la stratégie à une croissance mesurable", steps: [{ title: "Découverte", description: "Nous écoutons votre vision, votre activité et vos objectifs." }, { title: "Conception", description: "Des concepts clairs adaptés à votre marque et à votre public." }, { title: "Réalisation", description: "Un développement soigné pour le web, le mobile et les logiciels." }, { title: "Lancement", description: "Nous livrons, optimisons et soutenons votre produit partout dans le monde." }], ctaTitle: "Prêt à améliorer votre présence numérique?", ctaText: "Présentez-nous vos objectifs et nous créerons un site, une application ou une plateforme adaptative et optimisée pour la recherche.", ctaButton: "Parlons-en" },
    about: { eyebrow: "À propos", title: "Studio indépendant.", titleAccent: "Conception axée sur l’entreprise.", intro: "Arash Web Studio est un studio de conception et de développement numérique géré par Arash Ammarlooi. Depuis 2013, le studio crée des expériences numériques pratiques pour des organisations du monde entier.", statLabels: ["Années d’expérience", "Projets réalisés", "Pays desservis", "Engagement envers la qualité"], storyTitle: "Un studio flexible centré sur", storyTitleAccent: "vos objectifs", storyParagraphs: ["Arash Web Studio réunit stratégie, conception et développement dans un processus ciblé. Les clients disposent d’un point de contact clair du premier échange au lancement, avec l’appui de spécialistes de confiance lorsque le projet exige une expertise supplémentaire.", "Chaque projet est adapté à l’organisation, à son public et à son marché. L’objectif est de créer une expérience numérique utile, accessible et adaptative qui favorise une croissance durable."], imageAlt: "Globe représentant des entreprises servies dans le monde entier", valuesEyebrow: "Ce qui nous anime", valuesTitle: "Nos valeurs", values: [{ title: "Collaboration flexible", description: "Un studio central ciblé collabore avec des spécialistes indépendants de confiance lorsque le projet exige une expertise supplémentaire." }, { title: "Conception intentionnelle", description: "Chaque mise en page, interaction et décision technique doit servir le public et l’objectif de l’entreprise." }, { title: "Une vision axée sur l’entreprise", description: "La conception vise des résultats clairs comme une meilleure crédibilité, des demandes qualifiées, des réservations et des ventes." }, { title: "Partenariat durable", description: "Le processus privilégie une communication claire, un lancement fiable et une amélioration continue." }], ctaTitle: "Vous souhaitez un service attentif appuyé par", ctaAccent: "une expérience concrète?", ctaButton: "Nous joindre" },
    contact: { eyebrow: "Contact", title: "Créons quelque chose d’", titleAccent: "utile.", intro: "Présentez à Arash Web Studio vos objectifs, votre public, les pages ou fonctions requises, votre échéancier et le contenu disponible. Vous recevrez généralement une réponse dans les 24 heures.", directTitle: "Contacter le studio", directText: "Appelez, textez ou écrivez-nous pour discuter d’un nouveau site, d’une refonte, d’une boutique en ligne, d’un parcours de réservation, d’une application mobile ou d’une plateforme sur mesure.", phone: "Téléphone", email: "Courriel", serviceArea: "Zone desservie", serviceAreaValue: "Disponible pour les entreprises du monde entier", experience: "Plus de 13 ans d’expérience · projets réalisés dans 14 pays.", formTitle: "Démarrer votre projet", name: "Votre nom", emailPlaceholder: "Votre courriel", phonePlaceholder: "Téléphone (facultatif)", projectType: "Type de projet", projectOptions: options(["Site web d’entreprise", "Boutique en ligne", "Site de réservation ou de rendez-vous", "Publicité / Page de campagne", "Application mobile", "Logiciel sur mesure", "Autre"]), details: "Parlez-nous de votre entreprise, de vos objectifs, de votre public, de votre échéancier et des fonctions requises", sending: "Envoi en cours...", send: "Envoyer le message", success: "Message envoyé! Nous vous répondrons dans les 24 heures.", genericError: "Une erreur est survenue.", errorFallback: "Vous pouvez aussi nous écrire directement à" },
    metadata: { homeTitle: "Conception web, SEO et développement | Arash Web Studio", homeDescription: "Sites adaptatifs, commerce électronique, systèmes de réservation, applications mobiles et logiciels sur mesure pour les petites et moyennes entreprises du monde entier.", aboutTitle: "À propos d’Arash Web Studio", aboutDescription: "Découvrez l’approche d’Arash Web Studio en matière de conception adaptative, de SEO, de contenu, de développement et de croissance numérique durable.", contactTitle: "Contacter Arash Web Studio", contactDescription: "Contactez le studio pour discuter d’un site d’entreprise adaptatif, d’une boutique en ligne, d’un parcours de réservation, d’une application mobile ou d’un logiciel sur mesure." },
  },
  es: {
    nav: { home: "Inicio", about: "Nosotros", services: "Servicios", blog: "Blog", contact: "Contacto", startProject: "Iniciar un proyecto", primaryLabel: "Navegación principal", mobileLabel: "Navegación móvil", openMenu: "Abrir menú", closeMenu: "Cerrar menú", homeLabel: "Inicio de Arash Web Studio", languageLabel: "Idioma" },
    footer: { description: "Arash Web Studio diseña sitios adaptables, comercio electrónico, sistemas de reservas, aplicaciones móviles y software a medida para pequeñas y medianas empresas de todo el mundo.", pages: "Páginas", services: "Servicios", getInTouch: "Contacto", location: "Estudio digital remoto", serviceArea: "Trabajamos con clientes de todo el mundo", copyright: "Diseño web y soluciones digitales para todo el mundo.", serviceTitles: { "ecommerce-web-design": "Diseño de sitios de comercio electrónico", "booking-website-design": "Sitios de reservas y citas", "small-business-web-design": "Diseño web para pequeñas y medianas empresas", "mobile-app-design": "Diseño de aplicaciones móviles", "custom-software-development": "Desarrollo de software a medida", "brand-identity-design": "Diseño de marca e identidad visual" } },
    home: { eyebrow: "Web · SEO · Móvil · Software", title: "Experiencias digitales creadas para", titleAccent: "impulsar tu negocio.", intro: "Diseño y desarrollo web adaptable para pequeñas y medianas empresas de cualquier parte del mundo. Creamos sitios empresariales, tiendas en línea, experiencias de reservas y citas, páginas de campañas, aplicaciones móviles y software a medida.", primaryCta: "Inicia tu proyecto", secondaryCta: "Sobre el estudio", imageAlt: "Diseño web adaptable mostrado en un teléfono y un portátil", processEyebrow: "Cómo funciona", processTitle: "De la estrategia al crecimiento medible", steps: [{ title: "Descubrimiento", description: "Escuchamos tu visión, tu negocio y tus objetivos." }, { title: "Diseño", description: "Conceptos claros creados para tu marca y tu público." }, { title: "Desarrollo", description: "Desarrollo meticuloso para web, móvil y software." }, { title: "Lanzamiento", description: "Publicamos, optimizamos y damos soporte a tu producto en todo el mundo." }], ctaTitle: "¿Listo para mejorar tu presencia digital?", ctaText: "Cuéntanos tus objetivos y crearemos un sitio, una aplicación o una plataforma adaptable y preparada para buscadores.", ctaButton: "Hablemos" },
    about: { eyebrow: "Nosotros", title: "Estudio independiente.", titleAccent: "Diseño orientado al negocio.", intro: "Arash Web Studio es un estudio de diseño y desarrollo digital gestionado por Arash Ammarlooi. Desde 2013 crea experiencias digitales prácticas para organizaciones de todo el mundo.", statLabels: ["Años de experiencia", "Proyectos entregados", "Países alcanzados", "Compromiso con la calidad"], storyTitle: "Un estudio flexible centrado en", storyTitleAccent: "tus objetivos", storyParagraphs: ["Arash Web Studio reúne estrategia, diseño y desarrollo en un proceso enfocado. Los clientes cuentan con un punto de contacto claro desde la primera conversación hasta el lanzamiento, con especialistas de confianza cuando el proyecto requiere experiencia adicional.", "Cada trabajo se adapta a la organización, su público y su mercado. El objetivo es crear una experiencia digital útil, accesible y adaptable que apoye el crecimiento a largo plazo."], imageAlt: "Globo que representa empresas atendidas en todo el mundo", valuesEyebrow: "Lo que nos impulsa", valuesTitle: "Nuestros valores", values: [{ title: "Colaboración flexible", description: "Un estudio central enfocado trabaja con especialistas independientes de confianza cuando se necesita experiencia adicional." }, { title: "Diseño con propósito", description: "Cada composición, interacción y decisión técnica debe servir al público y al objetivo empresarial." }, { title: "Pensamiento empresarial", description: "El diseño se conecta con resultados claros como credibilidad, consultas cualificadas, reservas y ventas." }, { title: "Alianza a largo plazo", description: "El proceso incluye comunicación clara, un lanzamiento fiable y espacio para mejorar." }], ctaTitle: "¿Quieres un servicio atento respaldado por", ctaAccent: "experiencia real?", ctaButton: "Contáctanos" },
    contact: { eyebrow: "Contacto", title: "Hagamos algo", titleAccent: "útil.", intro: "Cuéntale a Arash Web Studio tus objetivos, público, páginas o funciones necesarias, plazo y contenido disponible. Normalmente recibirás una respuesta en 24 horas.", directTitle: "Contacta con el estudio", directText: "Llama, envía un mensaje o un correo para hablar de un nuevo sitio, rediseño, comercio electrónico, flujo de reservas, aplicación móvil o plataforma a medida.", phone: "Teléfono", email: "Correo electrónico", serviceArea: "Área de servicio", serviceAreaValue: "Disponible para empresas de todo el mundo", experience: "Más de 13 años de experiencia · proyectos entregados en 14 países.", formTitle: "Inicia tu proyecto", name: "Tu nombre", emailPlaceholder: "Tu correo electrónico", phonePlaceholder: "Teléfono (opcional)", projectType: "Tipo de proyecto", projectOptions: options(["Sitio web empresarial", "Tienda en línea", "Sitio de reservas o citas", "Publicidad / Página de campaña", "Aplicación móvil", "Software a medida", "Otro"]), details: "Cuéntanos sobre tu negocio, objetivos, público, plazo y funciones necesarias", sending: "Enviando...", send: "Enviar mensaje", success: "¡Mensaje enviado! Te responderemos en un plazo de 24 horas.", genericError: "Algo salió mal.", errorFallback: "También puedes escribirnos directamente a" },
    metadata: { homeTitle: "Diseño web, SEO y desarrollo | Arash Web Studio", homeDescription: "Sitios adaptables, comercio electrónico, sistemas de reservas, aplicaciones móviles y software a medida para pequeñas y medianas empresas de todo el mundo.", aboutTitle: "Sobre Arash Web Studio", aboutDescription: "Conoce el enfoque de Arash Web Studio sobre diseño adaptable, SEO, contenido, desarrollo y crecimiento digital a largo plazo.", contactTitle: "Contacta con Arash Web Studio", contactDescription: "Contacta con el estudio para hablar de un sitio empresarial adaptable, tienda en línea, experiencia de reservas, aplicación móvil o software a medida." },
  },
  de: {
    nav: { home: "Startseite", about: "Über uns", services: "Leistungen", blog: "Blog", contact: "Kontakt", startProject: "Projekt starten", primaryLabel: "Hauptnavigation", mobileLabel: "Mobile Navigation", openMenu: "Menü öffnen", closeMenu: "Menü schließen", homeLabel: "Arash Web Studio Startseite", languageLabel: "Sprache" },
    footer: { description: "Arash Web Studio gestaltet responsive Websites, E-Commerce-Erlebnisse, Buchungssysteme, mobile Apps und individuelle Software für kleine und mittlere Unternehmen weltweit.", pages: "Seiten", services: "Leistungen", getInTouch: "Kontakt", location: "Digitales Remote-Studio", serviceArea: "Zusammenarbeit mit Kunden weltweit", copyright: "Webdesign und digitale Lösungen weltweit.", serviceTitles: { "ecommerce-web-design": "E-Commerce-Webdesign", "booking-website-design": "Buchungs- und Terminwebsites", "small-business-web-design": "Webdesign für kleine und mittlere Unternehmen", "mobile-app-design": "Design mobiler Apps", "custom-software-development": "Individuelle Softwareentwicklung", "brand-identity-design": "Marken- und visuelles Identitätsdesign" } },
    home: { eyebrow: "Web · SEO · Mobil · Software", title: "Digitale Erlebnisse für", titleAccent: "nachhaltiges Wachstum.", intro: "Responsives Webdesign und Entwicklung für kleine und mittlere Unternehmen überall auf der Welt. Wir erstellen Unternehmenswebsites, Onlineshops, Buchungs- und Terminerlebnisse, Kampagnenseiten, mobile Apps und individuelle Software.", primaryCta: "Projekt starten", secondaryCta: "Über das Studio", imageAlt: "Responsives Webdesign auf einem Smartphone und Laptop", processEyebrow: "So funktioniert es", processTitle: "Von der Strategie zu messbarem Wachstum", steps: [{ title: "Entdecken", description: "Wir hören Ihrer Vision, Ihrem Unternehmen und Ihren Zielen zu." }, { title: "Gestalten", description: "Klare Konzepte, abgestimmt auf Ihre Marke und Zielgruppe." }, { title: "Entwickeln", description: "Sorgfältige Entwicklung für Web, Mobilgeräte und Software." }, { title: "Veröffentlichen", description: "Wir veröffentlichen, optimieren und betreuen Ihr Produkt weltweit." }], ctaTitle: "Bereit für einen stärkeren digitalen Auftritt?", ctaText: "Nennen Sie uns Ihre Ziele. Wir entwickeln eine responsive, suchoptimierte Website, App oder Plattform für Ihr Unternehmen.", ctaButton: "Lassen Sie uns sprechen" },
    about: { eyebrow: "Über uns", title: "Unabhängiges Studio.", titleAccent: "Unternehmensorientiertes Design.", intro: "Arash Web Studio ist ein von Arash Ammarlooi geführtes Studio für digitales Design und Entwicklung. Seit 2013 entstehen praktische digitale Erlebnisse für Organisationen weltweit.", statLabels: ["Jahre Erfahrung", "Abgeschlossene Projekte", "Erreichte Länder", "Verpflichtung zur Qualität"], storyTitle: "Ein flexibles Studio für", storyTitleAccent: "Ihre Ziele", storyParagraphs: ["Arash Web Studio verbindet Strategie, Design und Entwicklung in einem fokussierten Prozess. Kunden haben vom ersten Gespräch bis zum Start eine klare Anlaufstelle; bei Bedarf kommen bewährte Fachleute hinzu.", "Jedes Projekt richtet sich nach der Organisation, ihrer Zielgruppe und ihrem Markt. Ziel ist ein nützliches, barrierearmes und responsives digitales Erlebnis, das langfristiges Wachstum unterstützt."], imageAlt: "Globus als Symbol für Unternehmen weltweit", valuesEyebrow: "Was uns antreibt", valuesTitle: "Unsere Werte", values: [{ title: "Flexible Zusammenarbeit", description: "Ein fokussiertes Kernstudio arbeitet bei zusätzlichem Fachbedarf mit bewährten unabhängigen Spezialisten." }, { title: "Zweckmäßige Gestaltung", description: "Jedes Layout, jede Interaktion und technische Entscheidung dient der Zielgruppe und dem Geschäftsziel." }, { title: "Unternehmerisches Denken", description: "Design wird mit Ergebnissen wie Glaubwürdigkeit, qualifizierten Anfragen, Buchungen und Verkäufen verbunden." }, { title: "Langfristige Partnerschaft", description: "Der Prozess umfasst klare Kommunikation, einen verlässlichen Start und Raum für Verbesserungen." }], ctaTitle: "Sie wünschen aufmerksamen Service mit", ctaAccent: "echter Erfahrung?", ctaButton: "Kontakt aufnehmen" },
    contact: { eyebrow: "Kontakt", title: "Lassen Sie uns etwas", titleAccent: "Nützliches schaffen.", intro: "Beschreiben Sie Arash Web Studio Ihre Ziele, Zielgruppe, benötigten Seiten oder Funktionen, den Zeitplan und vorhandene Inhalte. In der Regel erhalten Sie innerhalb von 24 Stunden eine Antwort.", directTitle: "Studio kontaktieren", directText: "Rufen Sie an oder schreiben Sie eine SMS oder E-Mail, um eine neue Website, ein Redesign, E-Commerce, einen Buchungsablauf, eine mobile App oder eine individuelle Plattform zu besprechen.", phone: "Telefon", email: "E-Mail", serviceArea: "Einsatzgebiet", serviceAreaValue: "Für Unternehmen weltweit verfügbar", experience: "Über 13 Jahre Erfahrung · Projekte in 14 Ländern umgesetzt.", formTitle: "Projekt starten", name: "Ihr Name", emailPlaceholder: "Ihre E-Mail-Adresse", phonePlaceholder: "Telefon (optional)", projectType: "Projektart", projectOptions: options(["Unternehmenswebsite", "Onlineshop", "Buchungs- oder Terminwebsite", "Werbung / Kampagnenseite", "Mobile App", "Individuelle Software", "Etwas anderes"]), details: "Beschreiben Sie Unternehmen, Ziele, Zielgruppe, Zeitplan und benötigte Funktionen", sending: "Wird gesendet...", send: "Nachricht senden", success: "Nachricht gesendet! Wir melden uns innerhalb von 24 Stunden.", genericError: "Etwas ist schiefgelaufen.", errorFallback: "Sie können uns auch direkt eine E-Mail senden an" },
    metadata: { homeTitle: "Webdesign, SEO und Entwicklung | Arash Web Studio", homeDescription: "Responsive Websites, E-Commerce, Buchungssysteme, mobile Apps und individuelle Software für kleine und mittlere Unternehmen weltweit.", aboutTitle: "Über Arash Web Studio", aboutDescription: "Erfahren Sie, wie Arash Web Studio responsives Design, SEO, Inhalte, Entwicklung und langfristiges digitales Wachstum verbindet.", contactTitle: "Arash Web Studio kontaktieren", contactDescription: "Kontaktieren Sie das Studio für eine responsive Unternehmenswebsite, einen Onlineshop, ein Buchungserlebnis, eine mobile App oder individuelle Software." },
  },
  it: {
    nav: { home: "Home", about: "Chi siamo", services: "Servizi", blog: "Blog", contact: "Contatti", startProject: "Avvia un progetto", primaryLabel: "Navigazione principale", mobileLabel: "Navigazione mobile", openMenu: "Apri menu", closeMenu: "Chiudi menu", homeLabel: "Home di Arash Web Studio", languageLabel: "Lingua" },
    footer: { description: "Arash Web Studio progetta siti responsive, e-commerce, sistemi di prenotazione, app mobili e software su misura per piccole e medie imprese in tutto il mondo.", pages: "Pagine", services: "Servizi", getInTouch: "Contatti", location: "Studio digitale da remoto", serviceArea: "Collaboriamo con clienti in tutto il mondo", copyright: "Web design e soluzioni digitali in tutto il mondo.", serviceTitles: { "ecommerce-web-design": "Progettazione di siti e-commerce", "booking-website-design": "Siti per prenotazioni e appuntamenti", "small-business-web-design": "Web design per piccole e medie imprese", "mobile-app-design": "Progettazione di applicazioni mobili", "custom-software-development": "Sviluppo software su misura", "brand-identity-design": "Brand e identità visiva" } },
    home: { eyebrow: "Web · SEO · Mobile · Software", title: "Esperienze digitali create per", titleAccent: "far crescere il business.", intro: "Web design e sviluppo responsive per piccole e medie imprese ovunque nel mondo. Creiamo siti aziendali, negozi online, esperienze di prenotazione e appuntamento, pagine per campagne, app mobili e software su misura.", primaryCta: "Avvia il tuo progetto", secondaryCta: "Chi siamo", imageAlt: "Design web responsivo visualizzato su smartphone e laptop", processEyebrow: "Come funziona", processTitle: "Dalla strategia alla crescita misurabile", steps: [{ title: "Scoperta", description: "Ascoltiamo la tua visione, la tua attività e i tuoi obiettivi." }, { title: "Progettazione", description: "Concept essenziali creati per il tuo brand e il tuo pubblico." }, { title: "Sviluppo", description: "Sviluppo accurato per web, dispositivi mobili e software." }, { title: "Lancio", description: "Pubblichiamo, ottimizziamo e supportiamo il tuo prodotto in tutto il mondo." }], ctaTitle: "Vuoi migliorare la tua presenza digitale?", ctaText: "Raccontaci i tuoi obiettivi e creeremo un sito, un’app o una piattaforma responsive e pronta per i motori di ricerca.", ctaButton: "Parliamone" },
    about: { eyebrow: "Chi siamo", title: "Studio indipendente.", titleAccent: "Design orientato al business.", intro: "Arash Web Studio è uno studio di design e sviluppo digitale gestito da Arash Ammarlooi. Dal 2013 crea esperienze digitali pratiche per organizzazioni in tutto il mondo.", statLabels: ["Anni di esperienza", "Progetti consegnati", "Paesi raggiunti", "Impegno per la qualità"], storyTitle: "Uno studio flessibile costruito intorno ai", storyTitleAccent: "tuoi obiettivi", storyParagraphs: ["Arash Web Studio unisce strategia, design e sviluppo in un processo mirato. I clienti hanno un referente chiaro dal primo colloquio al lancio, con specialisti di fiducia quando servono competenze aggiuntive.", "Ogni progetto è modellato sull’organizzazione, il suo pubblico e il suo mercato. L’obiettivo è creare un’esperienza digitale utile, accessibile e responsive che sostenga la crescita nel tempo."], imageAlt: "Globo che rappresenta aziende servite in tutto il mondo", valuesEyebrow: "Ciò che ci guida", valuesTitle: "I nostri valori", values: [{ title: "Collaborazione flessibile", description: "Uno studio centrale e focalizzato collabora con specialisti indipendenti di fiducia quando servono competenze aggiuntive." }, { title: "Design consapevole", description: "Ogni layout, interazione e decisione tecnica deve servire il pubblico e l’obiettivo aziendale." }, { title: "Mentalità orientata al business", description: "Il design è collegato a risultati chiari come credibilità, richieste qualificate, prenotazioni e vendite." }, { title: "Partnership duratura", description: "Il processo comprende comunicazione chiara, un lancio affidabile e spazio per migliorare." }], ctaTitle: "Vuoi un servizio attento sostenuto da", ctaAccent: "esperienza concreta?", ctaButton: "Contattaci" },
    contact: { eyebrow: "Contatti", title: "Creiamo qualcosa di", titleAccent: "utile.", intro: "Racconta ad Arash Web Studio obiettivi, pubblico, pagine o funzioni necessarie, tempi e contenuti disponibili. Di solito riceverai una risposta entro 24 ore.", directTitle: "Contatta lo studio", directText: "Chiama, invia un messaggio o un’e-mail per parlare di un nuovo sito, un redesign, e-commerce, un flusso di prenotazione, un’app mobile o una piattaforma su misura.", phone: "Telefono", email: "E-mail", serviceArea: "Area servita", serviceAreaValue: "Disponibile per aziende in tutto il mondo", experience: "Oltre 13 anni di esperienza · progetti consegnati in 14 paesi.", formTitle: "Avvia il tuo progetto", name: "Il tuo nome", emailPlaceholder: "La tua e-mail", phonePlaceholder: "Telefono (facoltativo)", projectType: "Tipo di progetto", projectOptions: options(["Sito web aziendale", "Negozio e-commerce", "Sito per prenotazioni o appuntamenti", "Pubblicità / Pagina per campagna", "Applicazione mobile", "Software su misura", "Altro"]), details: "Raccontaci attività, obiettivi, pubblico, tempi e funzioni necessarie", sending: "Invio in corso...", send: "Invia messaggio", success: "Messaggio inviato! Ti risponderemo entro 24 ore.", genericError: "Qualcosa è andato storto.", errorFallback: "Puoi anche scriverci direttamente a" },
    metadata: { homeTitle: "Web design, SEO e sviluppo | Arash Web Studio", homeDescription: "Siti responsive, e-commerce, sistemi di prenotazione, app mobili e software su misura per piccole e medie imprese in tutto il mondo.", aboutTitle: "Chi è Arash Web Studio", aboutDescription: "Scopri l’approccio di Arash Web Studio a design responsive, SEO, contenuti, sviluppo e crescita digitale nel tempo.", contactTitle: "Contatta Arash Web Studio", contactDescription: "Contatta lo studio per un sito aziendale responsive, un negozio online, un’esperienza di prenotazione, un’app mobile o software su misura." },
  },
  pt: {
    nav: { home: "Início", about: "Sobre", services: "Serviços", blog: "Blog", contact: "Contato", startProject: "Iniciar um projeto", primaryLabel: "Navegação principal", mobileLabel: "Navegação móvel", openMenu: "Abrir menu", closeMenu: "Fechar menu", homeLabel: "Início da Arash Web Studio", languageLabel: "Idioma" },
    footer: { description: "A Arash Web Studio cria sites responsivos, comércio eletrónico, sistemas de reservas, aplicações móveis e software personalizado para pequenas e médias empresas em todo o mundo.", pages: "Páginas", services: "Serviços", getInTouch: "Entre em contato", location: "Estúdio digital remoto", serviceArea: "Colaboração com clientes em todo o mundo", copyright: "Web design e soluções digitais em todo o mundo.", serviceTitles: { "ecommerce-web-design": "Design de sites de comércio eletrónico", "booking-website-design": "Sites de reservas e marcações", "small-business-web-design": "Web design para pequenas e médias empresas", "mobile-app-design": "Design de aplicações móveis", "custom-software-development": "Desenvolvimento de software personalizado", "brand-identity-design": "Design de marca e identidade visual" } },
    home: { eyebrow: "Web · SEO · Mobile · Software", title: "Experiências digitais criadas para", titleAccent: "fazer o negócio crescer.", intro: "Web design e desenvolvimento responsivo para pequenas e médias empresas em qualquer parte do mundo. Criamos sites empresariais, lojas online, experiências de reservas e marcações, páginas de campanha, aplicações móveis e software personalizado.", primaryCta: "Inicie o seu projeto", secondaryCta: "Sobre o estúdio", imageAlt: "Design responsivo exibido num telemóvel e computador portátil", processEyebrow: "Como funciona", processTitle: "Da estratégia ao crescimento mensurável", steps: [{ title: "Descoberta", description: "Ouvimos a sua visão, o seu negócio e os seus objetivos." }, { title: "Design", description: "Conceitos claros criados para a sua marca e público." }, { title: "Desenvolvimento", description: "Desenvolvimento cuidadoso para web, mobile e software." }, { title: "Lançamento", description: "Publicamos, otimizamos e apoiamos o seu produto em todo o mundo." }], ctaTitle: "Pronto para melhorar a presença digital?", ctaText: "Conte-nos os seus objetivos e criaremos um site, aplicação ou plataforma responsiva e preparada para pesquisa.", ctaButton: "Vamos conversar" },
    about: { eyebrow: "Sobre", title: "Estúdio independente.", titleAccent: "Design orientado ao negócio.", intro: "A Arash Web Studio é um estúdio de design e desenvolvimento digital gerido por Arash Ammarlooi. Desde 2013, cria experiências digitais práticas para organizações em todo o mundo.", statLabels: ["Anos de experiência", "Projetos entregues", "Países alcançados", "Compromisso com a qualidade"], storyTitle: "Um estúdio flexível construído em torno dos", storyTitleAccent: "seus objetivos", storyParagraphs: ["A Arash Web Studio reúne estratégia, design e desenvolvimento num processo focado. Os clientes têm um ponto de contacto claro desde a primeira conversa até ao lançamento, com especialistas de confiança quando é necessária experiência adicional.", "Cada projeto é moldado à organização, ao seu público e mercado. O objetivo é criar uma experiência digital útil, acessível e responsiva que apoie o crescimento a longo prazo."], imageAlt: "Globo representando empresas atendidas em todo o mundo", valuesEyebrow: "O que nos move", valuesTitle: "Nossos valores", values: [{ title: "Colaboração flexível", description: "Um estúdio central focado colabora com especialistas independentes de confiança quando é necessária experiência adicional." }, { title: "Design com propósito", description: "Cada layout, interação e decisão técnica deve servir o público e o objetivo do negócio." }, { title: "Pensamento voltado ao negócio", description: "O design liga-se a resultados claros como credibilidade, pedidos qualificados, reservas e vendas." }, { title: "Parceria duradoura", description: "O processo inclui comunicação clara, um lançamento fiável e espaço para melhoria contínua." }], ctaTitle: "Quer um serviço atento apoiado por", ctaAccent: "experiência real?", ctaButton: "Entre em contato" },
    contact: { eyebrow: "Contato", title: "Vamos criar algo", titleAccent: "útil.", intro: "Conte à Arash Web Studio os seus objetivos, público, páginas ou funções necessárias, prazo e conteúdo disponível. Normalmente receberá uma resposta em 24 horas.", directTitle: "Contacte o estúdio", directText: "Ligue, envie uma mensagem ou um e-mail para falar sobre um novo site, reformulação, comércio eletrónico, fluxo de reservas, aplicação móvel ou plataforma personalizada.", phone: "Telefone", email: "E-mail", serviceArea: "Área de atendimento", serviceAreaValue: "Disponível para empresas em todo o mundo", experience: "Mais de 13 anos de experiência · projetos entregues em 14 países.", formTitle: "Inicie o seu projeto", name: "Seu nome", emailPlaceholder: "Seu e-mail", phonePlaceholder: "Telefone (opcional)", projectType: "Tipo de projeto", projectOptions: options(["Site empresarial", "Loja online", "Site de reservas ou marcações", "Publicidade / Página de campanha", "Aplicação móvel", "Software personalizado", "Outro"]), details: "Conte-nos sobre o negócio, objetivos, público, prazo e funções necessárias", sending: "Enviando...", send: "Enviar mensagem", success: "Mensagem enviada! Responderemos em 24 horas.", genericError: "Algo deu errado.", errorFallback: "Também pode enviar-nos um e-mail diretamente para" },
    metadata: { homeTitle: "Web design, SEO e desenvolvimento | Arash Web Studio", homeDescription: "Sites responsivos, comércio eletrónico, sistemas de reservas, aplicações móveis e software personalizado para pequenas e médias empresas em todo o mundo.", aboutTitle: "Sobre a Arash Web Studio", aboutDescription: "Conheça a abordagem da Arash Web Studio a design responsivo, SEO, conteúdo, desenvolvimento e crescimento digital a longo prazo.", contactTitle: "Contacte a Arash Web Studio", contactDescription: "Contacte o estúdio para falar sobre um site empresarial responsivo, loja online, experiência de reservas, aplicação móvel ou software personalizado." },
  },
  zh: {
    nav: { home: "首页", about: "关于我们", services: "服务", blog: "博客", contact: "联系", startProject: "启动项目", primaryLabel: "主导航", mobileLabel: "移动端导航", openMenu: "打开菜单", closeMenu: "关闭菜单", homeLabel: "Arash Web Studio 首页", languageLabel: "语言" },
    footer: { description: "Arash Web Studio 为全球中小型企业提供响应式网站、电子商务、预订系统、移动应用和定制软件设计服务。", pages: "页面", services: "服务", getInTouch: "联系我们", location: "远程数字工作室", serviceArea: "与全球客户合作", copyright: "面向全球的网站设计与数字解决方案。", serviceTitles: { "ecommerce-web-design": "电子商务网站设计", "booking-website-design": "预订与预约网站", "small-business-web-design": "中小型企业网站设计", "mobile-app-design": "移动应用设计", "custom-software-development": "定制软件开发", "brand-identity-design": "品牌与视觉识别设计" } },
    home: { eyebrow: "网站 · SEO · 移动应用 · 软件", title: "以业务增长为目标的", titleAccent: "数字体验。", intro: "为全球中小型企业提供响应式网站设计与开发。我们打造企业网站、电子商务商店、预订与预约体验、营销活动页面、移动应用及定制软件。", primaryCta: "启动您的项目", secondaryCta: "了解工作室", imageAlt: "在手机和笔记本电脑上展示的响应式网站设计", processEyebrow: "合作流程", processTitle: "从策略到可衡量的增长", steps: [{ title: "了解", description: "我们倾听您的愿景、业务需求和目标。" }, { title: "设计", description: "围绕您的品牌与受众打造清晰的设计方案。" }, { title: "开发", description: "精心完成网站、移动应用与软件开发。" }, { title: "上线", description: "我们面向全球发布、优化并持续支持您的产品。" }], ctaTitle: "准备好提升数字形象了吗？", ctaText: "告诉我们您的目标，我们将围绕业务打造响应式且搜索友好的网站、应用或平台。", ctaButton: "联系我们" },
    about: { eyebrow: "关于我们", title: "独立工作室，", titleAccent: "以业务为导向。", intro: "Arash Web Studio 是一家由 Arash Ammarlooi 管理的数字设计与开发工作室。自 2013 年以来，工作室为全球组织打造实用的数字体验。", statLabels: ["年行业经验", "已交付项目", "服务覆盖国家", "对品质的承诺"], storyTitle: "灵活的工作室，围绕", storyTitleAccent: "您的目标打造", storyParagraphs: ["Arash Web Studio 将策略、设计和开发整合为专注的流程。客户从首次沟通到上线都有明确的联系人；项目需要额外能力时，则由值得信赖的专业人员参与。", "每个项目都围绕组织、受众和市场展开。目标是打造实用、无障碍且响应式的数字体验，为长期增长提供支持。"], imageAlt: "代表全球服务企业的地球图像", valuesEyebrow: "我们的动力", valuesTitle: "我们的价值观", values: [{ title: "灵活协作", description: "专注的核心工作室会在项目需要额外能力时与值得信赖的独立专业人员协作。" }, { title: "目标明确的设计", description: "每个布局、交互和技术决策都应服务于受众和业务目标。" }, { title: "以业务为先", description: "设计与信誉、有效咨询、预订和销售等明确成果相连接。" }, { title: "长期合作", description: "流程包含清晰沟通、可靠上线以及持续改进的空间。" }], ctaTitle: "希望获得由真实经验支撑的", ctaAccent: "周到服务吗？", ctaButton: "联系我们" },
    contact: { eyebrow: "联系我们", title: "让我们一起打造", titleAccent: "实用的产品。", intro: "请向 Arash Web Studio 介绍您的目标、受众、所需页面或功能、时间安排及现有内容。您通常会在 24 小时内收到回复。", directTitle: "联系工作室", directText: "您可以致电、发短信或发送电子邮件，讨论新网站、改版、电子商务、预订流程、移动应用或定制平台。", phone: "电话", email: "电子邮件", serviceArea: "服务范围", serviceAreaValue: "服务全球企业", experience: "13 年以上经验 · 已在 14 个国家交付项目。", formTitle: "启动您的项目", name: "您的姓名", emailPlaceholder: "您的电子邮箱", phonePlaceholder: "电话（选填）", projectType: "项目类型", projectOptions: options(["企业网站", "电子商务商店", "预订或预约网站", "广告 / 营销活动页面", "移动应用", "定制软件", "其他"]), details: "请介绍您的业务、目标、受众、时间安排和所需功能", sending: "正在发送……", send: "发送消息", success: "消息已发送！我们将在 24 小时内回复您。", genericError: "出现错误。", errorFallback: "您也可以直接发送电子邮件至" },
    metadata: { homeTitle: "网站设计、SEO 与开发 | Arash Web Studio", homeDescription: "为全球中小型企业提供响应式网站、电子商务、预订系统、移动应用和定制软件。", aboutTitle: "关于 Arash Web Studio", aboutDescription: "了解 Arash Web Studio 如何结合响应式设计、SEO、内容、开发与长期数字增长。", contactTitle: "联系 Arash Web Studio", contactDescription: "联系工作室，讨论响应式企业网站、电子商务商店、预订体验、移动应用或定制软件项目。" },
  },
};

export function getPageTranslations(locale: Locale) {
  return pageTranslations[locale];
}
